using Distribution.Application.DTOs;
using Distribution.Domain.Entities;

namespace Distribution.Infrastructure.Services;

/// <summary>
/// Entity → DTO projections shared across the services.
///
/// Hand-written rather than reflective on purpose: several of these carry derived fields
/// (days-to-expiry, effective credit limit, achievement pace) that only make sense against a
/// clock, and a convention-based mapper would silently drop them.
///
/// Roll-up fields that need a second query — outlet counts, month-to-date sales, credit — are
/// left at their defaults here and filled by the calling service, which knows whether the caller
/// is paying for them.
/// </summary>
public static class DistributionMapper
{
    // ── Network ──────────────────────────────────────────────────────────────

    public static PartnerDto ToDto(this ChannelPartner e) => new()
    {
        Id = e.Id,
        Code = e.Code,
        Name = e.Name,
        TradeName = e.TradeName,
        PartnerType = e.PartnerType,
        Status = e.Status,
        ServicingModel = e.ServicingModel,
        ParentPartnerId = e.ParentPartnerId,
        ParentPartnerName = e.ParentPartner?.Name,
        ContactPerson = e.ContactPerson,
        Phone = e.Phone,
        AlternatePhone = e.AlternatePhone,
        Email = e.Email,
        AddressLine = e.AddressLine,
        City = e.City,
        StateName = e.StateName,
        PostalCode = e.PostalCode,
        CountryCode = e.CountryCode,
        Latitude = e.Latitude,
        Longitude = e.Longitude,
        TaxRegistrationNumber = e.TaxRegistrationNumber,
        SecondaryTaxNumber = e.SecondaryTaxNumber,
        TerritoryId = e.TerritoryId,
        TerritoryName = e.Territory?.Name,
        ServicingWarehouseId = e.ServicingWarehouseId,
        PartnerWarehouseId = e.PartnerWarehouseId,
        PriceListId = e.PriceListId,
        CrmAccountId = e.CrmAccountId,
        CurrencyCode = e.CurrencyCode,
        CreditLimit = e.CreditLimit,
        CreditDays = e.CreditDays,
        CreditEnforcement = e.CreditEnforcement,
        SecurityDeposit = e.SecurityDeposit,
        MarginPercent = e.MarginPercent,
        MinimumMonthlyOfftake = e.MinimumMonthlyOfftake,
        AppointedOn = e.AppointedOn,
        AgreementExpiresOn = e.AgreementExpiresOn,
        TerminatedOn = e.TerminatedOn,
        TerminationReason = e.TerminationReason,
        StatusReason = e.StatusReason,
        SecondaryCaptureMode = e.SecondaryCaptureMode,
        PortalUserId = e.PortalUserId,
        Notes = e.Notes,
        IsActive = e.IsActive,
        Contacts = e.Contacts.Select(c => c.ToDto()).ToList(),
        Documents = e.Documents.Select(d => d.ToDto()).ToList(),
        Authorisations = e.Authorisations.Select(a => a.ToDto()).ToList(),
    };

    public static PartnerContactDto ToDto(this PartnerContact e) => new()
    {
        Id = e.Id,
        FullName = e.FullName,
        Designation = e.Designation,
        Phone = e.Phone,
        Email = e.Email,
        IsPrimary = e.IsPrimary,
        HandlesClaims = e.HandlesClaims,
        HandlesPayments = e.HandlesPayments,
    };

    public static PartnerDocumentDto ToDto(this PartnerDocument e) => new()
    {
        Id = e.Id,
        DocumentType = e.DocumentType,
        DocumentNumber = e.DocumentNumber,
        FileUrl = e.FileUrl,
        IssuedOn = e.IssuedOn,
        ExpiresOn = e.ExpiresOn,
        IsVerified = e.IsVerified,
        VerifiedAt = e.VerifiedAt,
        VerificationNote = e.VerificationNote,
        DaysToExpiry = e.ExpiresOn is null ? null : (int)(e.ExpiresOn.Value.Date - DateTime.UtcNow.Date).TotalDays,
    };

    public static PartnerAuthorisationDto ToDto(this PartnerAuthorisation e) => new()
    {
        Id = e.Id,
        BrandId = e.BrandId,
        CategoryId = e.CategoryId,
        ItemId = e.ItemId,
        ScopeName = e.ScopeName,
        EffectiveFrom = e.EffectiveFrom,
        EffectiveTo = e.EffectiveTo,
        IsExclusive = e.IsExclusive,
    };

    public static OutletDto ToDto(this RetailOutlet e) => new()
    {
        Id = e.Id,
        Code = e.Code,
        Name = e.Name,
        OwnerName = e.OwnerName,
        OwnerPhone = e.OwnerPhone,
        DecisionMakerName = e.DecisionMakerName,
        AlternatePhone = e.AlternatePhone,
        Email = e.Email,
        Channel = e.Channel,
        SubChannel = e.SubChannel,
        Grade = e.Grade,
        Status = e.Status,
        StatusReason = e.StatusReason,
        ChainName = e.ChainName,
        StoreFormat = e.StoreFormat,
        ShelfCount = e.ShelfCount,
        HasRefrigeration = e.HasRefrigeration,
        AddressLine = e.AddressLine,
        Landmark = e.Landmark,
        Area = e.Area,
        City = e.City,
        StateName = e.StateName,
        PostalCode = e.PostalCode,
        CountryCode = e.CountryCode,
        Latitude = e.Latitude,
        Longitude = e.Longitude,
        GeofenceRadiusMetres = e.GeofenceRadiusMetres,
        GeoNodeId = e.GeoNodeId,
        PartnerId = e.PartnerId,
        PartnerName = e.Partner?.Name,
        TerritoryId = e.TerritoryId,
        PriceListId = e.PriceListId,
        SchemeGroupId = e.SchemeGroupId,
        CrmContactId = e.CrmContactId,
        CurrencyCode = e.CurrencyCode,
        CreditLimit = e.CreditLimit,
        CreditDays = e.CreditDays,
        CreditEnforcement = e.CreditEnforcement,
        PreferredTender = e.PreferredTender,
        TaxRegistrationNumber = e.TaxRegistrationNumber,
        LicenceNumber = e.LicenceNumber,
        LicenceExpiresOn = e.LicenceExpiresOn,
        OpensAt = e.OpensAt,
        ClosesAt = e.ClosesAt,
        WeeklyOffDay = e.WeeklyOffDay,
        PreferredDeliveryFrom = e.PreferredDeliveryFrom,
        PreferredDeliveryTo = e.PreferredDeliveryTo,
        OnboardedAt = e.OnboardedAt,
        FirstOrderAt = e.FirstOrderAt,
        LastVisitAt = e.LastVisitAt,
        LastOrderAt = e.LastOrderAt,
        LastPaymentAt = e.LastPaymentAt,
        LifetimeSales = e.LifetimeSales,
        AverageMonthlyOfftake = e.AverageMonthlyOfftake,
        OutstandingAmount = e.OutstandingAmount,
        TotalVisits = e.TotalVisits,
        ProductiveVisits = e.ProductiveVisits,
        PerfectStoreScore = e.PerfectStoreScore,
        PhotoUrl = e.PhotoUrl,
        Notes = e.Notes,
        IsApproved = e.IsApproved,
        IsActive = e.IsActive,
        DaysSinceLastVisit = e.LastVisitAt is null
            ? null
            : (int)(DateTime.UtcNow.Date - e.LastVisitAt.Value.Date).TotalDays,
        Assets = e.Assets.Select(a => a.ToDto()).ToList(),
        Contacts = e.Contacts.Select(c => c.ToDto()).ToList(),
    };

    public static OutletContactDto ToDto(this OutletContact e) => new()
    {
        Id = e.Id,
        FullName = e.FullName,
        Designation = e.Designation,
        Phone = e.Phone,
        Email = e.Email,
        IsPrimary = e.IsPrimary,
    };

    public static OutletAssetDto ToDto(this OutletAsset e) => new()
    {
        Id = e.Id,
        OutletId = e.OutletId,
        OutletName = e.Outlet?.Name,
        Kind = e.Kind,
        AssetTag = e.AssetTag,
        SerialNumber = e.SerialNumber,
        Model = e.Model,
        Manufacturer = e.Manufacturer,
        PlacedOn = e.PlacedOn,
        RetrievedOn = e.RetrievedOn,
        AssetValue = e.AssetValue,
        DepositTaken = e.DepositTaken,
        Condition = e.Condition,
        LastVerifiedAt = e.LastVerifiedAt,
        ServiceDueOn = e.ServiceDueOn,
        PhotoUrl = e.PhotoUrl,
        Note = e.Note,
        DaysSinceVerified = e.LastVerifiedAt is null
            ? null
            : (int)(DateTime.UtcNow.Date - e.LastVerifiedAt.Value.Date).TotalDays,
    };

    public static OutletPhotoDto ToDto(this OutletPhoto e) => new()
    {
        Id = e.Id,
        OutletId = e.OutletId,
        VisitId = e.VisitId,
        ImageUrl = e.ImageUrl,
        Caption = e.Caption,
        Tag = e.Tag,
        CapturedAt = e.CapturedAt,
        PairedPhotoId = e.PairedPhotoId,
    };

    public static OutletNoteDto ToDto(this OutletNote e) => new()
    {
        Id = e.Id,
        OutletId = e.OutletId,
        Text = e.Text,
        AuthorName = e.AuthorName,
        NotedAt = e.NotedAt,
        IsPinned = e.IsPinned,
    };

    // ── Routes ───────────────────────────────────────────────────────────────

    public static GeoNodeDto ToDto(this GeoNode e) => new()
    {
        Id = e.Id,
        Code = e.Code,
        Name = e.Name,
        ParentId = e.ParentId,
        LevelName = e.LevelName,
        Depth = e.Depth,
        Path = e.Path,
        ManagerUserId = e.ManagerUserId,
        Latitude = e.Latitude,
        Longitude = e.Longitude,
        IsActive = e.IsActive,
    };

    public static TerritoryDto ToDto(this DistributionTerritory e) => new()
    {
        Id = e.Id,
        Code = e.Code,
        Name = e.Name,
        ParentId = e.ParentId,
        ParentName = e.Parent?.Name,
        GeoNodeId = e.GeoNodeId,
        GeoNodeName = e.GeoNode?.Name,
        ManagerFieldRepId = e.ManagerFieldRepId,
        DefaultPartnerId = e.DefaultPartnerId,
        DefaultWarehouseId = e.DefaultWarehouseId,
        CurrencyCode = e.CurrencyCode,
        IsActive = e.IsActive,
        Description = e.Description,
    };

    public static RouteDto ToDto(this SalesRoute e) => new()
    {
        Id = e.Id,
        Code = e.Code,
        Name = e.Name,
        Kind = e.Kind,
        Frequency = e.Frequency,
        TerritoryId = e.TerritoryId,
        TerritoryName = e.Territory?.Name,
        PartnerId = e.PartnerId,
        PartnerName = e.Partner?.Name,
        FieldRepId = e.FieldRepId,
        FieldRepName = e.FieldRep?.FullName,
        VehicleId = e.VehicleId,
        VanUnitId = e.VanUnitId,
        WarehouseId = e.WarehouseId,
        ActiveDays = e.ActiveDays,
        ActiveWeeks = e.ActiveWeeks,
        StartTime = e.StartTime,
        EndTime = e.EndTime,
        TargetCallsPerDay = e.TargetCallsPerDay,
        MinimumProductiveCalls = e.MinimumProductiveCalls,
        PlannedDistanceKm = e.PlannedDistanceKm,
        PlannedDurationMinutes = e.PlannedDurationMinutes,
        OutletCount = e.OutletCount,
        LastRunAt = e.LastRunAt,
        IsActive = e.IsActive,
        Description = e.Description,
    };

    public static RouteStopDto ToStopDto(this RouteOutlet e) => new()
    {
        Id = e.Id,
        OutletId = e.OutletId,
        OutletName = e.Outlet?.Name ?? string.Empty,
        OutletCode = e.Outlet?.Code,
        Channel = e.Outlet?.Channel ?? default,
        Grade = e.Outlet?.Grade ?? default,
        Status = e.Outlet?.Status ?? default,
        AddressLine = e.Outlet?.AddressLine,
        Latitude = e.Outlet?.Latitude,
        Longitude = e.Outlet?.Longitude,
        StopSequence = e.StopSequence,
        ServiceMinutes = e.ServiceMinutes,
        DistanceFromPreviousKm = e.DistanceFromPreviousKm,
        FrequencyOverride = e.FrequencyOverride,
        IsMustVisit = e.IsMustVisit,
        OutstandingAmount = e.Outlet?.OutstandingAmount ?? 0,
        LastVisitAt = e.Outlet?.LastVisitAt,
    };

    public static JourneyPlanDto ToDto(this JourneyPlan e) => new()
    {
        Id = e.Id,
        FieldRepId = e.FieldRepId,
        FieldRepName = e.FieldRep?.FullName,
        TerritoryId = e.TerritoryId,
        PeriodStart = e.PeriodStart,
        PeriodEnd = e.PeriodEnd,
        Name = e.Name,
        IsPublished = e.IsPublished,
        PublishedAt = e.PublishedAt,
        PlannedCalls = e.PlannedCalls,
        ActualCalls = e.ActualCalls,
        ProductiveCalls = e.ProductiveCalls,
        UnplannedCalls = e.UnplannedCalls,
        MissedCalls = e.MissedCalls,
        CoveragePercent = Percent(e.ActualCalls, e.PlannedCalls),
        StrikeRatePercent = Percent(e.ProductiveCalls, e.ActualCalls),
        Days = e.Days.OrderBy(d => d.PlanDate).Select(d => d.ToDto()).ToList(),
    };

    public static JourneyPlanDayDto ToDto(this JourneyPlanDay e) => new()
    {
        Id = e.Id,
        PlanDate = e.PlanDate,
        RouteId = e.RouteId,
        RouteName = e.Route?.Name,
        RouteKind = e.Route?.Kind,
        Status = e.Status,
        ReassignedToFieldRepId = e.ReassignedToFieldRepId,
        SkipReason = e.SkipReason,
        PlannedCalls = e.PlannedCalls,
        ActualCalls = e.ActualCalls,
        ProductiveCalls = e.ProductiveCalls,
        FieldDayId = e.FieldDayId,
    };

    // ── Field ────────────────────────────────────────────────────────────────

    public static FieldRepDto ToDto(this FieldRep e) => new()
    {
        Id = e.Id,
        Code = e.Code,
        FullName = e.FullName,
        DisplayName = e.DisplayName,
        Role = e.Role,
        Phone = e.Phone,
        Email = e.Email,
        PhotoUrl = e.PhotoUrl,
        UserId = e.UserId,
        EmployeeId = e.EmployeeId,
        PartnerId = e.PartnerId,
        PartnerName = e.Partner?.Name,
        TerritoryId = e.TerritoryId,
        ReportsToFieldRepId = e.ReportsToFieldRepId,
        DefaultVanUnitId = e.DefaultVanUnitId,
        DefaultWarehouseId = e.DefaultWarehouseId,
        JoinedOn = e.JoinedOn,
        LeftOn = e.LeftOn,
        CashHoldingLimit = e.CashHoldingLimit,
        DiscountAuthorityPercent = e.DiscountAuthorityPercent,
        CanOnboardOutlets = e.CanOnboardOutlets,
        CanCollectPayments = e.CanCollectPayments,
        CanAcceptReturns = e.CanAcceptReturns,
        HasPin = !string.IsNullOrEmpty(e.PinHash),
        IsActive = e.IsActive,
        Note = e.Note,
    };

    public static FieldDeviceDto ToDto(this FieldDevice e) => new()
    {
        Id = e.Id,
        FieldRepId = e.FieldRepId,
        FieldRepName = e.FieldRep?.FullName,
        DeviceIdentifier = e.DeviceIdentifier,
        DeviceName = e.DeviceName,
        Platform = e.Platform,
        OsVersion = e.OsVersion,
        AppVersion = e.AppVersion,
        RegisteredAt = e.RegisteredAt,
        LastSeenAt = e.LastSeenAt,
        LastSyncAt = e.LastSyncAt,
        PendingOutboxCount = e.PendingOutboxCount,
        IsBlocked = e.IsBlocked,
        BlockReason = e.BlockReason,
        WipeRequested = e.WipeRequested,
        WipedAt = e.WipedAt,
        MinutesSinceSync = e.LastSyncAt is null
            ? null
            : (int)(DateTime.UtcNow - e.LastSyncAt.Value).TotalMinutes,
    };

    public static FieldDayDto ToDto(this FieldDay e) => new()
    {
        Id = e.Id,
        FieldRepId = e.FieldRepId,
        FieldRepName = e.FieldRep?.FullName,
        WorkDate = e.WorkDate,
        RouteId = e.RouteId,
        RouteName = e.Route?.Name,
        RouteKind = e.Route?.Kind,
        VanUnitId = e.VanUnitId,
        Status = e.Status,
        StartedAt = e.StartedAt,
        ClosedAt = e.ClosedAt,
        StartLatitude = e.StartLatitude,
        StartLongitude = e.StartLongitude,
        StartSelfieUrl = e.StartSelfieUrl,
        DistanceCoveredKm = e.DistanceCoveredKm,
        PlannedCalls = e.PlannedCalls,
        ActualCalls = e.ActualCalls,
        ProductiveCalls = e.ProductiveCalls,
        UnplannedCalls = e.UnplannedCalls,
        NewOutletsAdded = e.NewOutletsAdded,
        DistinctLinesSold = e.DistinctLinesSold,
        OrderValue = e.OrderValue,
        InvoicedValue = e.InvoicedValue,
        CollectedAmount = e.CollectedAmount,
        ReturnValue = e.ReturnValue,
        CashDeclared = e.CashDeclared,
        UnsyncedCount = e.UnsyncedCount,
        LastSyncAt = e.LastSyncAt,
        ForceCloseReason = e.ForceCloseReason,
        Note = e.Note,
        CoveragePercent = Percent(e.ActualCalls, e.PlannedCalls),
        StrikeRatePercent = Percent(e.ProductiveCalls, e.ActualCalls),
        LinesPerCall = e.ProductiveCalls == 0 ? 0 : Math.Round((decimal)e.DistinctLinesSold / e.ProductiveCalls, 2),
    };

    public static VisitDto ToDto(this OutletVisit e) => new()
    {
        Id = e.Id,
        FieldDayId = e.FieldDayId,
        OutletId = e.OutletId,
        OutletName = e.Outlet?.Name,
        RouteId = e.RouteId,
        FieldRepId = e.FieldRepId,
        StopSequence = e.StopSequence,
        Status = e.Status,
        IsPlanned = e.IsPlanned,
        CheckedInAt = e.CheckedInAt,
        CheckedOutAt = e.CheckedOutAt,
        CheckInLatitude = e.CheckInLatitude,
        CheckInLongitude = e.CheckInLongitude,
        GeoValidation = e.GeoValidation,
        DistanceFromOutletMetres = e.DistanceFromOutletMetres,
        GeoExceptionReason = e.GeoExceptionReason,
        DurationMinutes = e.DurationMinutes,
        IsProductive = e.IsProductive,
        NoOrderReasonId = e.NoOrderReasonId,
        NoOrderNote = e.NoOrderNote,
        OrderId = e.OrderId,
        OrderValue = e.OrderValue,
        LinesSold = e.LinesSold,
        CollectedAmount = e.CollectedAmount,
        ReturnValue = e.ReturnValue,
        MustSellSoldCount = e.MustSellSoldCount,
        MustSellTargetCount = e.MustSellTargetCount,
        SurveyCompleted = e.SurveyCompleted,
        AuditCompleted = e.AuditCompleted,
        AssetsVerified = e.AssetsVerified,
        Note = e.Note,
    };

    public static VisitSummaryDto ToSummary(this OutletVisit e) => new()
    {
        Id = e.Id,
        OutletId = e.OutletId,
        OutletName = e.Outlet?.Name,
        CheckedInAt = e.CheckedInAt,
        DurationMinutes = e.DurationMinutes,
        Status = e.Status,
        GeoValidation = e.GeoValidation,
        IsProductive = e.IsProductive,
        IsPlanned = e.IsPlanned,
        OrderValue = e.OrderValue,
        CollectedAmount = e.CollectedAmount,
    };

    public static VisitTaskDto ToDto(this VisitTask e) => new()
    {
        Id = e.Id,
        Title = e.Title,
        Instructions = e.Instructions,
        OutletId = e.OutletId,
        RouteId = e.RouteId,
        TerritoryId = e.TerritoryId,
        FieldRepId = e.FieldRepId,
        DueOn = e.DueOn,
        CompletedAt = e.CompletedAt,
        RequiresPhoto = e.RequiresPhoto,
        PhotoUrl = e.PhotoUrl,
        CompletionNote = e.CompletionNote,
        Priority = e.Priority,
        IsMandatory = e.IsMandatory,
        IsOverdue = e.CompletedAt is null && e.DueOn.Date < DateTime.UtcNow.Date,
    };

    public static SurveyFormDto ToDto(this SurveyForm e) => new()
    {
        Id = e.Id,
        Name = e.Name,
        Instructions = e.Instructions,
        ActiveFrom = e.ActiveFrom,
        ActiveTo = e.ActiveTo,
        ApplicableChannels = e.ApplicableChannels,
        TerritoryId = e.TerritoryId,
        RouteId = e.RouteId,
        IsMandatory = e.IsMandatory,
        RepeatEveryVisit = e.RepeatEveryVisit,
        IsActive = e.IsActive,
        Questions = e.Questions.OrderBy(q => q.DisplayOrder).Select(q => q.ToDto()).ToList(),
    };

    public static SurveyQuestionDto ToDto(this SurveyQuestion e) => new()
    {
        Id = e.Id,
        Text = e.Text,
        Kind = e.Kind,
        DisplayOrder = e.DisplayOrder,
        IsRequired = e.IsRequired,
        Options = e.Options,
        MinValue = e.MinValue,
        MaxValue = e.MaxValue,
        Unit = e.Unit,
        Guidance = e.Guidance,
        ShowWhenQuestionId = e.ShowWhenQuestionId,
        ShowWhenValue = e.ShowWhenValue,
    };

    public static MerchandisingAuditDto ToDto(this MerchandisingAudit e) => new()
    {
        Id = e.Id,
        OutletId = e.OutletId,
        OutletName = e.Outlet?.Name,
        VisitId = e.VisitId,
        FieldRepId = e.FieldRepId,
        Kind = e.Kind,
        AuditedAt = e.AuditedAt,
        Score = e.Score,
        MaxScore = e.MaxScore,
        AvailabilityScore = e.AvailabilityScore,
        VisibilityScore = e.VisibilityScore,
        PlanogramScore = e.PlanogramScore,
        PricingScore = e.PricingScore,
        PosmScore = e.PosmScore,
        ShareOfShelfPercent = e.ShareOfShelfPercent,
        OnShelfAvailabilityPercent = e.OnShelfAvailabilityPercent,
        BeforePhotoUrl = e.BeforePhotoUrl,
        AfterPhotoUrl = e.AfterPhotoUrl,
        Note = e.Note,
        Lines = e.Lines.Select(l => l.ToDto()).ToList(),
    };

    public static MerchandisingAuditLineDto ToDto(this MerchandisingAuditLine e) => new()
    {
        Id = e.Id,
        ItemId = e.ItemId,
        ItemName = e.ItemName,
        ItemCode = e.ItemCode,
        IsExpectedInAssortment = e.IsExpectedInAssortment,
        IsPresent = e.IsPresent,
        Facings = e.Facings,
        ExpectedFacings = e.ExpectedFacings,
        ShelfStock = e.ShelfStock,
        ObservedPrice = e.ObservedPrice,
        MandatedPrice = e.MandatedPrice,
        IsPriceCompliant = e.IsPriceCompliant,
        IsCorrectPosition = e.IsCorrectPosition,
        Note = e.Note,
    };

    // ── Van ──────────────────────────────────────────────────────────────────

    public static VanUnitDto ToDto(this VanUnit e) => new()
    {
        Id = e.Id,
        Code = e.Code,
        Name = e.Name,
        WarehouseId = e.WarehouseId,
        HomeWarehouseId = e.HomeWarehouseId,
        VehicleId = e.VehicleId,
        VehicleRegistration = e.Vehicle?.RegistrationNumber,
        FieldRepId = e.FieldRepId,
        FieldRepName = e.FieldRep?.FullName,
        RouteId = e.RouteId,
        CapacityWeightKg = e.CapacityWeightKg,
        CapacityVolumeM3 = e.CapacityVolumeM3,
        IsRefrigerated = e.IsRefrigerated,
        MinSafeCelsius = e.MinSafeCelsius,
        MaxSafeCelsius = e.MaxSafeCelsius,
        IsMultiDay = e.IsMultiDay,
        LastLoadedAt = e.LastLoadedAt,
        LastSettledAt = e.LastSettledAt,
        IsActive = e.IsActive,
        Note = e.Note,
    };

    public static VanStockBalanceDto ToDto(this VanStockBalance e) => new()
    {
        Id = e.Id,
        VanUnitId = e.VanUnitId,
        ItemId = e.ItemId,
        ItemName = e.ItemName,
        ItemCode = e.ItemCode,
        BatchId = e.BatchId,
        BatchNumber = e.BatchNumber,
        ExpiryDate = e.ExpiryDate,
        Compartment = e.Compartment,
        Uom = e.Uom,
        Quantity = e.Quantity,
        ReservedQuantity = e.ReservedQuantity,
        AvailableQuantity = e.Quantity - e.ReservedQuantity,
        UnitCost = e.UnitCost,
        UnitPrice = e.UnitPrice,
        StockValue = e.Quantity * e.UnitCost,
        LastMovementAt = e.LastMovementAt,
        DaysToExpiry = e.ExpiryDate is null ? null : (int)(e.ExpiryDate.Value.Date - DateTime.UtcNow.Date).TotalDays,
    };

    public static VanStockMovementDto ToDto(this VanStockMovement e) => new()
    {
        Id = e.Id,
        Kind = e.Kind,
        OccurredAt = e.OccurredAt,
        ItemId = e.ItemId,
        ItemName = e.ItemName,
        BatchNumber = e.BatchNumber,
        Compartment = e.Compartment,
        Uom = e.Uom,
        Quantity = e.Quantity,
        BalanceAfter = e.BalanceAfter,
        Value = e.Value,
        ReferenceType = e.ReferenceType,
        ReferenceNumber = e.ReferenceNumber,
        Reason = e.Reason,
    };

    public static VanLoadSheetDto ToDto(this VanLoadSheet e) => new()
    {
        Id = e.Id,
        LoadNumber = e.LoadNumber,
        VanUnitId = e.VanUnitId,
        VanUnitName = e.VanUnit?.Name,
        RouteId = e.RouteId,
        FieldRepId = e.FieldRepId,
        FieldDayId = e.FieldDayId,
        SourceWarehouseId = e.SourceWarehouseId,
        LoadDate = e.LoadDate,
        Status = e.Status,
        IsSuggested = e.IsSuggested,
        ApprovedAt = e.ApprovedAt,
        LoadedAt = e.LoadedAt,
        RejectionReason = e.RejectionReason,
        TotalCostValue = e.TotalCostValue,
        TotalSaleValue = e.TotalSaleValue,
        TotalWeightKg = e.TotalWeightKg,
        VarianceLineCount = e.VarianceLineCount,
        Note = e.Note,
        Lines = e.Lines.OrderBy(l => l.DisplayOrder).Select(l => l.ToDto()).ToList(),
    };

    public static VanLoadLineDto ToDto(this VanLoadLine e) => new()
    {
        Id = e.Id,
        DisplayOrder = e.DisplayOrder,
        ItemId = e.ItemId,
        ItemName = e.ItemName,
        ItemCode = e.ItemCode,
        BatchId = e.BatchId,
        BatchNumber = e.BatchNumber,
        ExpiryDate = e.ExpiryDate,
        Uom = e.Uom,
        UomFactor = e.UomFactor,
        SuggestedQuantity = e.SuggestedQuantity,
        RequestedQuantity = e.RequestedQuantity,
        ApprovedQuantity = e.ApprovedQuantity,
        PickedQuantity = e.PickedQuantity,
        LoadedQuantity = e.LoadedQuantity,
        UnitCost = e.UnitCost,
        UnitPrice = e.UnitPrice,
        LineValue = e.LineValue,
        Compartment = e.Compartment,
        VarianceReason = e.VarianceReason,
    };

    public static VanCycleCountDto ToDto(this VanCycleCount e) => new()
    {
        Id = e.Id,
        CountNumber = e.CountNumber,
        VanUnitId = e.VanUnitId,
        VanUnitName = e.VanUnit?.Name,
        FieldDayId = e.FieldDayId,
        FieldRepId = e.FieldRepId,
        CountedAt = e.CountedAt,
        IsFullCount = e.IsFullCount,
        IsBlind = e.IsBlind,
        LineCount = e.LineCount,
        VarianceLineCount = e.VarianceLineCount,
        VarianceValue = e.VarianceValue,
        IsApproved = e.IsApproved,
        Note = e.Note,
        Lines = e.Lines.Select(l => l.ToDto()).ToList(),
    };

    public static VanCycleCountLineDto ToDto(this VanCycleCountLine e) => new()
    {
        Id = e.Id,
        ItemId = e.ItemId,
        ItemName = e.ItemName,
        BatchId = e.BatchId,
        BatchNumber = e.BatchNumber,
        ExpiryDate = e.ExpiryDate,
        Compartment = e.Compartment,
        Uom = e.Uom,
        ExpectedQuantity = e.ExpectedQuantity,
        CountedQuantity = e.CountedQuantity,
        VarianceQuantity = e.VarianceQuantity,
        UnitCost = e.UnitCost,
        VarianceValue = e.VarianceValue,
        ReasonCodeId = e.ReasonCodeId,
        ReasonNote = e.ReasonNote,
        IsAdjusted = e.IsAdjusted,
    };

    // ── Orders ───────────────────────────────────────────────────────────────

    public static DistributionOrderDto ToDto(this DistributionOrder e) => new()
    {
        Id = e.Id,
        OrderNumber = e.OrderNumber,
        Source = e.Source,
        Kind = e.Kind,
        Status = e.Status,
        OutletId = e.OutletId,
        OutletName = e.Outlet?.Name,
        OutletCode = e.Outlet?.Code,
        OutletChannel = e.Outlet?.Channel,
        PartnerId = e.PartnerId,
        PartnerName = e.Partner?.Name,
        CustomerName = e.CustomerName,
        CustomerPhone = e.CustomerPhone,
        VisitId = e.VisitId,
        FieldDayId = e.FieldDayId,
        FieldRepId = e.FieldRepId,
        RouteId = e.RouteId,
        TerritoryId = e.TerritoryId,
        WarehouseId = e.WarehouseId,
        VanUnitId = e.VanUnitId,
        TripId = e.TripId,
        LinkedPurchaseOrderId = e.LinkedPurchaseOrderId,
        SalesOrderId = e.SalesOrderId,
        SalesInvoiceId = e.SalesInvoiceId,
        OrderDate = e.OrderDate,
        RequestedDeliveryDate = e.RequestedDeliveryDate,
        PromisedDeliveryDate = e.PromisedDeliveryDate,
        DispatchedAt = e.DispatchedAt,
        DeliveredAt = e.DeliveredAt,
        CurrencyCode = e.CurrencyCode,
        ExchangeRate = e.ExchangeRate,
        SubTotal = e.SubTotal,
        DiscountAmount = e.DiscountAmount,
        SchemeDiscountAmount = e.SchemeDiscountAmount,
        FreeGoodsValue = e.FreeGoodsValue,
        TaxAmount = e.TaxAmount,
        FreightAmount = e.FreightAmount,
        RoundingAmount = e.RoundingAmount,
        TotalAmount = e.TotalAmount,
        PaidAmount = e.PaidAmount,
        CostAmount = e.CostAmount,
        MarginAmount = e.MarginAmount,
        MarginPercent = e.SubTotal == 0 ? 0 : Math.Round(e.MarginAmount / e.SubTotal * 100, 2),
        RequiresApproval = e.RequiresApproval,
        ApprovedAt = e.ApprovedAt,
        HoldReason = e.HoldReason,
        RejectionReason = e.RejectionReason,
        CancelNote = e.CancelNote,
        HasCreditOverride = e.HasCreditOverride,
        IsBackorderParent = e.IsBackorderParent,
        BackorderOfOrderId = e.BackorderOfOrderId,
        LineCount = e.LineCount,
        TotalQuantity = e.TotalQuantity,
        FillRatePercent = e.FillRatePercent,
        ExternalReference = e.ExternalReference,
        Note = e.Note,
        Lines = e.Lines.OrderBy(l => l.DisplayOrder).Select(l => l.ToDto()).ToList(),
        StatusEvents = e.StatusEvents.OrderBy(s => s.OccurredAt).Select(s => s.ToDto()).ToList(),
        Approvals = e.Approvals.OrderBy(a => a.StepNumber).Select(a => a.ToDto()).ToList(),
    };

    public static OrderSummaryDto ToSummary(this DistributionOrder e) => new()
    {
        Id = e.Id,
        OrderNumber = e.OrderNumber,
        OrderDate = e.OrderDate,
        Status = e.Status,
        Source = e.Source,
        Kind = e.Kind,
        OutletId = e.OutletId,
        OutletName = e.Outlet?.Name,
        PartnerId = e.PartnerId,
        PartnerName = e.Partner?.Name,
        CurrencyCode = e.CurrencyCode,
        TotalAmount = e.TotalAmount,
        PaidAmount = e.PaidAmount,
        LineCount = e.LineCount,
        FillRatePercent = e.FillRatePercent,
        PromisedDeliveryDate = e.PromisedDeliveryDate,
        RequiresApproval = e.RequiresApproval,
        IsOverdueForDelivery = e.PromisedDeliveryDate is not null
            && e.DeliveredAt is null
            && e.PromisedDeliveryDate.Value.Date < DateTime.UtcNow.Date,
    };

    public static DistributionOrderLineDto ToDto(this DistributionOrderLine e) => new()
    {
        Id = e.Id,
        DisplayOrder = e.DisplayOrder,
        ItemId = e.ItemId,
        ItemName = e.ItemName,
        ItemCode = e.ItemCode,
        BrandId = e.BrandId,
        CategoryId = e.CategoryId,
        BatchId = e.BatchId,
        BatchNumber = e.BatchNumber,
        ExpiryDate = e.ExpiryDate,
        Uom = e.Uom,
        UomFactor = e.UomFactor,
        Quantity = e.Quantity,
        BaseQuantity = e.BaseQuantity,
        AllocatedQuantity = e.AllocatedQuantity,
        PickedQuantity = e.PickedQuantity,
        DispatchedQuantity = e.DispatchedQuantity,
        DeliveredQuantity = e.DeliveredQuantity,
        ReturnedQuantity = e.ReturnedQuantity,
        BackorderedQuantity = e.BackorderedQuantity,
        UnitPrice = e.UnitPrice,
        Mrp = e.Mrp,
        DiscountPercent = e.DiscountPercent,
        DiscountAmount = e.DiscountAmount,
        SchemeDiscountAmount = e.SchemeDiscountAmount,
        TaxPercent = e.TaxPercent,
        TaxAmount = e.TaxAmount,
        LineTotal = e.LineTotal,
        UnitCost = e.UnitCost,
        MarginAmount = e.MarginAmount,
        IsFreeGoods = e.IsFreeGoods,
        SchemeId = e.SchemeId,
        SchemeName = e.SchemeName,
        PriceScope = e.PriceScope,
        IsPriceOverridden = e.IsPriceOverridden,
        PriceOverrideReason = e.PriceOverrideReason,
        IsShortPicked = e.IsShortPicked,
        Note = e.Note,
    };

    public static OrderStatusEventDto ToDto(this OrderStatusEvent e) => new()
    {
        FromStatus = e.FromStatus,
        ToStatus = e.ToStatus,
        OccurredAt = e.OccurredAt,
        ActorName = e.ActorName,
        Note = e.Note,
    };

    public static OrderApprovalDto ToDto(this OrderApproval e) => new()
    {
        Id = e.Id,
        StepNumber = e.StepNumber,
        StepName = e.StepName,
        TriggerReason = e.TriggerReason,
        ApproverName = e.ApproverName,
        IsApproved = e.IsApproved,
        DecidedAt = e.DecidedAt,
        Comment = e.Comment,
        IsEscalated = e.IsEscalated,
    };

    // ── Trade ────────────────────────────────────────────────────────────────

    public static TradeSchemeDto ToDto(this TradeScheme e) => new()
    {
        Id = e.Id,
        SchemeNumber = e.SchemeNumber,
        Name = e.Name,
        Kind = e.Kind,
        Status = e.Status,
        SettlementMode = e.SettlementMode,
        Stacking = e.Stacking,
        StackingGroup = e.StackingGroup,
        Priority = e.Priority,
        ValidFrom = e.ValidFrom,
        ValidTo = e.ValidTo,
        ActiveDays = e.ActiveDays,
        MinQuantity = e.MinQuantity,
        MinValue = e.MinValue,
        FreeQuantity = e.FreeQuantity,
        FreeItemId = e.FreeItemId,
        FreeItemName = e.FreeItemName,
        FreeItemUom = e.FreeItemUom,
        DiscountPercent = e.DiscountPercent,
        DiscountAmount = e.DiscountAmount,
        MaxBenefitPerOrder = e.MaxBenefitPerOrder,
        MaxBenefitPerOutlet = e.MaxBenefitPerOutlet,
        IsRecurringPerBlock = e.IsRecurringPerBlock,
        IsPeriodScheme = e.IsPeriodScheme,
        PaymentWithinDays = e.PaymentWithinDays,
        DisplayDurationDays = e.DisplayDurationDays,
        DisplayPayout = e.DisplayPayout,
        RequiresPhotoEvidence = e.RequiresPhotoEvidence,
        CurrencyCode = e.CurrencyCode,
        BudgetAmount = e.BudgetAmount,
        ConsumedAmount = e.ConsumedAmount,
        RemainingBudget = e.BudgetAmount - e.ConsumedAmount,
        BudgetUsedPercent = e.BudgetAmount == 0 ? 0 : Math.Round(e.ConsumedAmount / e.BudgetAmount * 100, 2),
        StopWhenBudgetExhausted = e.StopWhenBudgetExhausted,
        ApprovedAt = e.ApprovedAt,
        RejectionReason = e.RejectionReason,
        CommunicationPackUrl = e.CommunicationPackUrl,
        TermsAndConditions = e.TermsAndConditions,
        Note = e.Note,
        ApplicationCount = e.ApplicationCount,
        BeneficiaryOutletCount = e.BeneficiaryOutletCount,
        QualifyingSalesValue = e.QualifyingSalesValue,
        IsActive = e.IsActive,
        Slabs = e.Slabs.OrderBy(s => s.SlabNumber).Select(s => s.ToDto()).ToList(),
        Products = e.Products.Select(p => p.ToDto()).ToList(),
        Scopes = e.Scopes.Select(s => s.ToDto()).ToList(),
    };

    public static TradeSchemeSlabDto ToDto(this TradeSchemeSlab e) => new()
    {
        Id = e.Id,
        SlabNumber = e.SlabNumber,
        FromQuantity = e.FromQuantity,
        ToQuantity = e.ToQuantity,
        FromValue = e.FromValue,
        ToValue = e.ToValue,
        FreeQuantity = e.FreeQuantity,
        DiscountPercent = e.DiscountPercent,
        DiscountAmount = e.DiscountAmount,
        PayoutAmount = e.PayoutAmount,
        PointsAwarded = e.PointsAwarded,
        FreeItemId = e.FreeItemId,
        FreeItemName = e.FreeItemName,
        Label = e.Label,
    };

    public static TradeSchemeProductDto ToDto(this TradeSchemeProduct e) => new()
    {
        Id = e.Id,
        ItemId = e.ItemId,
        ItemName = e.ItemName,
        BrandId = e.BrandId,
        CategoryId = e.CategoryId,
        IsQualifying = e.IsQualifying,
        RequiredQuantity = e.RequiredQuantity,
        Uom = e.Uom,
        UomFactor = e.UomFactor,
        IsExcluded = e.IsExcluded,
    };

    public static TradeSchemeScopeDto ToDto(this TradeSchemeScope e) => new()
    {
        Id = e.Id,
        Channel = e.Channel,
        OutletGrade = e.OutletGrade,
        PartnerTier = e.PartnerTier,
        TerritoryId = e.TerritoryId,
        RouteId = e.RouteId,
        PartnerId = e.PartnerId,
        OutletId = e.OutletId,
        IsExcluded = e.IsExcluded,
    };

    public static SchemeApplicationDto ToDto(this SchemeApplication e) => new()
    {
        Id = e.Id,
        SchemeId = e.SchemeId,
        SchemeName = e.SchemeName,
        SchemeKind = e.SchemeKind,
        OrderId = e.OrderId,
        OrderLineId = e.OrderLineId,
        OutletId = e.OutletId,
        PartnerId = e.PartnerId,
        AppliedAt = e.AppliedAt,
        QualifyingQuantity = e.QualifyingQuantity,
        QualifyingValue = e.QualifyingValue,
        SlabNumber = e.SlabNumber,
        FreeQuantity = e.FreeQuantity,
        FreeItemId = e.FreeItemId,
        FreeItemName = e.FreeItemName,
        DiscountAmount = e.DiscountAmount,
        PayoutAmount = e.PayoutAmount,
        PointsAwarded = e.PointsAwarded,
        BenefitValue = e.BenefitValue,
        SettlementMode = e.SettlementMode,
        ClaimId = e.ClaimId,
        IsSettled = e.IsSettled,
        BenefitDescription = e.BenefitDescription,
        IsReversed = e.IsReversed,
    };

    public static PriceListDto ToDto(this ChannelPriceList e) => new()
    {
        Id = e.Id,
        Code = e.Code,
        Name = e.Name,
        Scope = e.Scope,
        Channel = e.Channel,
        TerritoryId = e.TerritoryId,
        PartnerTier = e.PartnerTier,
        PartnerId = e.PartnerId,
        OutletId = e.OutletId,
        CurrencyCode = e.CurrencyCode,
        EffectiveFrom = e.EffectiveFrom,
        EffectiveTo = e.EffectiveTo,
        Priority = e.Priority,
        IsTaxInclusive = e.IsTaxInclusive,
        IsApproved = e.IsApproved,
        ApprovedAt = e.ApprovedAt,
        SupersedesPriceListId = e.SupersedesPriceListId,
        IsActive = e.IsActive,
        Description = e.Description,
        LineCount = e.Lines.Count,
        Lines = e.Lines.Select(l => l.ToDto()).ToList(),
    };

    public static PriceListLineDto ToDto(this ChannelPriceListLine e) => new()
    {
        Id = e.Id,
        ItemId = e.ItemId,
        ItemName = e.ItemName,
        ItemCode = e.ItemCode,
        BrandId = e.BrandId,
        CategoryId = e.CategoryId,
        Uom = e.Uom,
        UomFactor = e.UomFactor,
        UnitPrice = e.UnitPrice,
        Mrp = e.Mrp,
        MinimumPrice = e.MinimumPrice,
        MaxDiscountPercent = e.MaxDiscountPercent,
        TaxPercent = e.TaxPercent,
        EffectiveFrom = e.EffectiveFrom,
        EffectiveTo = e.EffectiveTo,
        Slabs = e.Slabs.OrderBy(s => s.FromQuantity).Select(s => s.ToDto()).ToList(),
    };

    public static PriceSlabDto ToDto(this PriceSlab e) => new()
    {
        Id = e.Id,
        FromQuantity = e.FromQuantity,
        ToQuantity = e.ToQuantity,
        UnitPrice = e.UnitPrice,
        DiscountPercent = e.DiscountPercent,
        DisplayOrder = e.DisplayOrder,
    };

    // ── Money ────────────────────────────────────────────────────────────────

    public static CreditSnapshotDto ToSnapshot(this CreditProfile e) => new()
    {
        OutletId = e.OutletId,
        PartnerId = e.PartnerId,
        CurrencyCode = e.CurrencyCode,
        CreditLimit = e.CreditLimit,
        TemporaryLimit = e.TemporaryLimit,
        TemporaryLimitExpiresOn = e.TemporaryLimitExpiresOn,
        EffectiveLimit = EffectiveLimit(e),
        CreditDays = e.CreditDays,
        Enforcement = e.Enforcement,
        OutstandingAmount = e.OutstandingAmount,
        OverdueAmount = e.OverdueAmount,
        UnbilledOrderValue = e.UnbilledOrderValue,
        AvailableCredit = e.AvailableCredit,
        Bucket0To30 = e.Bucket0To30,
        Bucket31To60 = e.Bucket31To60,
        Bucket61To90 = e.Bucket61To90,
        Bucket90Plus = e.Bucket90Plus,
        OldestInvoiceDays = e.OldestInvoiceDays,
        LastPaymentAt = e.LastPaymentAt,
        LastPaymentAmount = e.LastPaymentAmount,
        IsBlocked = e.IsBlocked,
        BlockReason = e.BlockReason,
        BouncedChequeCount = e.BouncedChequeCount,
        SecurityDeposit = e.SecurityDeposit,
        AdvanceHeld = e.AdvanceHeld,
        ProvisionedAmount = e.ProvisionedAmount,
        RecalculatedAt = e.RecalculatedAt,
    };

    public static CreditProfileDto ToDto(this CreditProfile e)
    {
        var snap = e.ToSnapshot();
        return new CreditProfileDto
        {
            Id = e.Id,
            OutletId = snap.OutletId,
            PartnerId = snap.PartnerId,
            OutletName = e.Outlet?.Name,
            OutletCode = e.Outlet?.Code,
            Channel = e.Outlet?.Channel,
            PartnerName = e.Partner?.Name,
            CurrencyCode = snap.CurrencyCode,
            CreditLimit = snap.CreditLimit,
            TemporaryLimit = snap.TemporaryLimit,
            TemporaryLimitExpiresOn = snap.TemporaryLimitExpiresOn,
            EffectiveLimit = snap.EffectiveLimit,
            CreditDays = snap.CreditDays,
            Enforcement = snap.Enforcement,
            OutstandingAmount = snap.OutstandingAmount,
            OverdueAmount = snap.OverdueAmount,
            UnbilledOrderValue = snap.UnbilledOrderValue,
            AvailableCredit = snap.AvailableCredit,
            Bucket0To30 = snap.Bucket0To30,
            Bucket31To60 = snap.Bucket31To60,
            Bucket61To90 = snap.Bucket61To90,
            Bucket90Plus = snap.Bucket90Plus,
            OldestInvoiceDays = snap.OldestInvoiceDays,
            LastPaymentAt = snap.LastPaymentAt,
            LastPaymentAmount = snap.LastPaymentAmount,
            IsBlocked = snap.IsBlocked,
            BlockReason = snap.BlockReason,
            BouncedChequeCount = snap.BouncedChequeCount,
            SecurityDeposit = snap.SecurityDeposit,
            AdvanceHeld = snap.AdvanceHeld,
            ProvisionedAmount = snap.ProvisionedAmount,
            RecalculatedAt = snap.RecalculatedAt,
        };
    }

    /// <summary>
    /// Limit plus any temporary uplift that has not lapsed. An expired override contributes
    /// nothing, which is the whole point of giving it a date.
    /// </summary>
    public static decimal EffectiveLimit(CreditProfile e)
        => e.CreditLimit + (e.TemporaryLimitExpiresOn is null || e.TemporaryLimitExpiresOn.Value.Date >= DateTime.UtcNow.Date
            ? e.TemporaryLimit
            : 0);

    public static CollectionDto ToDto(this CollectionReceipt e) => new()
    {
        Id = e.Id,
        ReceiptNumber = e.ReceiptNumber,
        OutletId = e.OutletId,
        OutletName = e.Outlet?.Name,
        PartnerId = e.PartnerId,
        VisitId = e.VisitId,
        FieldDayId = e.FieldDayId,
        FieldRepId = e.FieldRepId,
        TripId = e.TripId,
        SettlementId = e.SettlementId,
        CollectedAt = e.CollectedAt,
        Tender = e.Tender,
        CurrencyCode = e.CurrencyCode,
        Amount = e.Amount,
        CashDiscountAmount = e.CashDiscountAmount,
        CashDiscountSchemeId = e.CashDiscountSchemeId,
        ChequeId = e.ChequeId,
        Reference = e.Reference,
        BankName = e.BankName,
        CardLast4 = e.CardLast4,
        CardScheme = e.CardScheme,
        AllocatedAmount = e.AllocatedAmount,
        UnallocatedAmount = e.UnallocatedAmount,
        IsDeposited = e.IsDeposited,
        IsReversed = e.IsReversed,
        ReversalReason = e.ReversalReason,
        ReceiptSentTo = e.ReceiptSentTo,
        Note = e.Note,
    };

    public static CollectionSummaryDto ToSummary(this CollectionReceipt e) => new()
    {
        Id = e.Id,
        ReceiptNumber = e.ReceiptNumber,
        CollectedAt = e.CollectedAt,
        Tender = e.Tender,
        Amount = e.Amount,
        CurrencyCode = e.CurrencyCode,
        OutletName = e.Outlet?.Name,
        Reference = e.Reference,
        IsDeposited = e.IsDeposited,
    };

    public static ChequeDto ToDto(this ChequeRecord e) => new()
    {
        Id = e.Id,
        ChequeNumber = e.ChequeNumber,
        OutletId = e.OutletId,
        PartnerId = e.PartnerId,
        CollectionReceiptId = e.CollectionReceiptId,
        BankName = e.BankName,
        BranchName = e.BranchName,
        AccountName = e.AccountName,
        Amount = e.Amount,
        CurrencyCode = e.CurrencyCode,
        ChequeDate = e.ChequeDate,
        ReceivedOn = e.ReceivedOn,
        IsPostDated = e.IsPostDated,
        Status = e.Status,
        DepositedOn = e.DepositedOn,
        DepositBankAccount = e.DepositBankAccount,
        ClearedOn = e.ClearedOn,
        BouncedOn = e.BouncedOn,
        BounceReason = e.BounceReason,
        BounceCharges = e.BounceCharges,
        TriggeredCreditBlock = e.TriggeredCreditBlock,
        Note = e.Note,
        DaysToMaturity = e.IsPostDated ? (int)(e.ChequeDate.Date - DateTime.UtcNow.Date).TotalDays : null,
    };

    public static ClaimDto ToDto(this ChannelClaim e, int slaDays) => new()
    {
        Id = e.Id,
        ClaimNumber = e.ClaimNumber,
        Kind = e.Kind,
        Status = e.Status,
        PartnerId = e.PartnerId,
        PartnerName = e.Partner?.Name,
        OutletId = e.OutletId,
        TerritoryId = e.TerritoryId,
        PeriodStart = e.PeriodStart,
        PeriodEnd = e.PeriodEnd,
        SubmittedOn = e.SubmittedOn,
        SchemeId = e.SchemeId,
        SchemeName = e.Scheme?.Name,
        ReturnId = e.ReturnId,
        MrpRevisionId = e.MrpRevisionId,
        CurrencyCode = e.CurrencyCode,
        ClaimedAmount = e.ClaimedAmount,
        ComputedAmount = e.ComputedAmount,
        VarianceAmount = e.VarianceAmount,
        ApprovedAmount = e.ApprovedAmount,
        SettledAmount = e.SettledAmount,
        IsSystemGenerated = e.IsSystemGenerated,
        ReviewStartedAt = e.ReviewStartedAt,
        QueryNote = e.QueryNote,
        QueriedAt = e.QueriedAt,
        ResubmittedAt = e.ResubmittedAt,
        DecidedAt = e.DecidedAt,
        RejectionNote = e.RejectionNote,
        SettlementMode = e.SettlementMode,
        SettledAt = e.SettledAt,
        CreditNoteId = e.CreditNoteId,
        SettlementReference = e.SettlementReference,
        SettlementDays = e.SettlementDays,
        AgeingDays = e.AgeingDays,
        IsBreachingSla = IsOpen(e.Status) && e.AgeingDays > slaDays,
        Note = e.Note,
        Lines = e.Lines.OrderBy(l => l.DisplayOrder).Select(l => l.ToDto()).ToList(),
        Documents = e.Documents.Select(d => d.ToDto()).ToList(),
        StatusEvents = e.StatusEvents.OrderBy(s => s.OccurredAt).Select(s => s.ToDto()).ToList(),
    };

    public static ClaimSummaryDto ToSummary(this ChannelClaim e, int slaDays) => new()
    {
        Id = e.Id,
        ClaimNumber = e.ClaimNumber,
        Kind = e.Kind,
        Status = e.Status,
        PartnerName = e.Partner?.Name,
        SchemeName = e.Scheme?.Name,
        SubmittedOn = e.SubmittedOn,
        CurrencyCode = e.CurrencyCode,
        ClaimedAmount = e.ClaimedAmount,
        ComputedAmount = e.ComputedAmount,
        ApprovedAmount = e.ApprovedAmount,
        VarianceAmount = e.VarianceAmount,
        AgeingDays = e.AgeingDays,
        IsBreachingSla = IsOpen(e.Status) && e.AgeingDays > slaDays,
        IsSystemGenerated = e.IsSystemGenerated,
        LineCount = e.Lines.Count,
        DocumentCount = e.Documents.Count,
    };

    public static ClaimLineDto ToDto(this ChannelClaimLine e) => new()
    {
        Id = e.Id,
        DisplayOrder = e.DisplayOrder,
        ItemId = e.ItemId,
        ItemName = e.ItemName,
        BatchId = e.BatchId,
        BatchNumber = e.BatchNumber,
        SourceInvoiceId = e.SourceInvoiceId,
        SourceInvoiceNumber = e.SourceInvoiceNumber,
        SourceOrderId = e.SourceOrderId,
        SchemeApplicationId = e.SchemeApplicationId,
        Uom = e.Uom,
        Quantity = e.Quantity,
        UnitRate = e.UnitRate,
        ClaimedAmount = e.ClaimedAmount,
        ComputedAmount = e.ComputedAmount,
        ApprovedAmount = e.ApprovedAmount,
        RejectionReasonCodeId = e.RejectionReasonCodeId,
        RejectionNote = e.RejectionNote,
        Note = e.Note,
    };

    public static ClaimDocumentDto ToDto(this ClaimDocument e) => new()
    {
        Id = e.Id,
        DocumentType = e.DocumentType,
        FileUrl = e.FileUrl,
        FileName = e.FileName,
        UploadedAt = e.UploadedAt,
        Note = e.Note,
    };

    public static ClaimStatusEventDto ToDto(this ClaimStatusEvent e) => new()
    {
        FromStatus = e.FromStatus,
        ToStatus = e.ToStatus,
        OccurredAt = e.OccurredAt,
        ActorName = e.ActorName,
        Note = e.Note,
    };

    public static SettlementDto ToDto(this RouteSettlement e) => new()
    {
        Id = e.Id,
        SettlementNumber = e.SettlementNumber,
        SettlementDate = e.SettlementDate,
        Status = e.Status,
        FieldRepId = e.FieldRepId,
        FieldRepName = e.FieldRep?.FullName,
        RouteId = e.RouteId,
        FieldDayId = e.FieldDayId,
        VanUnitId = e.VanUnitId,
        TripId = e.TripId,
        PartnerId = e.PartnerId,
        CurrencyCode = e.CurrencyCode,
        InvoiceCount = e.InvoiceCount,
        CashSalesValue = e.CashSalesValue,
        CreditSalesValue = e.CreditSalesValue,
        TotalSalesValue = e.TotalSalesValue,
        TaxValue = e.TaxValue,
        DiscountValue = e.DiscountValue,
        SchemeValue = e.SchemeValue,
        FreeGoodsValue = e.FreeGoodsValue,
        ReturnValue = e.ReturnValue,
        CashCollected = e.CashCollected,
        ChequeCollected = e.ChequeCollected,
        DigitalCollected = e.DigitalCollected,
        TotalCollected = e.TotalCollected,
        OpeningFloat = e.OpeningFloat,
        ExpectedCash = e.ExpectedCash,
        DeclaredCash = e.DeclaredCash,
        CashVariance = e.CashVariance,
        ExpenseAmount = e.ExpenseAmount,
        CashToDeposit = e.CashToDeposit,
        OpeningStockValue = e.OpeningStockValue,
        LoadedStockValue = e.LoadedStockValue,
        SoldStockValue = e.SoldStockValue,
        ReturnedStockValue = e.ReturnedStockValue,
        ExpectedClosingStockValue = e.ExpectedClosingStockValue,
        CountedClosingStockValue = e.CountedClosingStockValue,
        StockVarianceValue = e.StockVarianceValue,
        ClosingCountId = e.ClosingCountId,
        VarianceCount = e.VarianceCount,
        UnexplainedVarianceCount = e.UnexplainedVarianceCount,
        SubmittedAt = e.SubmittedAt,
        ApprovedAt = e.ApprovedAt,
        ClosedAt = e.ClosedAt,
        IsPartial = e.IsPartial,
        IsReversed = e.IsReversed,
        ReversalReason = e.ReversalReason,
        IsPosted = e.IsPosted,
        Note = e.Note,
        Variances = e.Variances.Select(v => v.ToDto()).ToList(),
    };

    public static SettlementVarianceDto ToDto(this SettlementVariance e) => new()
    {
        Id = e.Id,
        Kind = e.Kind,
        ItemId = e.ItemId,
        ItemName = e.ItemName,
        BatchId = e.BatchId,
        BatchNumber = e.BatchNumber,
        Uom = e.Uom,
        ExpectedQuantity = e.ExpectedQuantity,
        ActualQuantity = e.ActualQuantity,
        VarianceQuantity = e.VarianceQuantity,
        ExpectedAmount = e.ExpectedAmount,
        ActualAmount = e.ActualAmount,
        VarianceAmount = e.VarianceAmount,
        ReasonCodeId = e.ReasonCodeId,
        ReasonNote = e.ReasonNote,
        RequiresApproval = e.RequiresApproval,
        IsApproved = e.IsApproved,
        IsRecoverable = e.IsRecoverable,
        RecoveredAmount = e.RecoveredAmount,
    };

    public static CashDepositDto ToDto(this CashDeposit e) => new()
    {
        Id = e.Id,
        DepositNumber = e.DepositNumber,
        FieldRepId = e.FieldRepId,
        SettlementId = e.SettlementId,
        PartnerId = e.PartnerId,
        DepositedOn = e.DepositedOn,
        BankName = e.BankName,
        BankAccount = e.BankAccount,
        SlipReference = e.SlipReference,
        SlipImageUrl = e.SlipImageUrl,
        Amount = e.Amount,
        CurrencyCode = e.CurrencyCode,
        IsReconciled = e.IsReconciled,
        ReconciledAt = e.ReconciledAt,
        AgeingDays = e.AgeingDays,
        Note = e.Note,
    };

    // ── Logistics ────────────────────────────────────────────────────────────

    public static VehicleDto ToDto(this Vehicle e) => new()
    {
        Id = e.Id,
        Code = e.Code,
        RegistrationNumber = e.RegistrationNumber,
        Name = e.Name,
        Kind = e.Kind,
        Ownership = e.Ownership,
        Make = e.Make,
        Model = e.Model,
        ManufactureYear = e.ManufactureYear,
        FuelType = e.FuelType,
        CapacityWeightKg = e.CapacityWeightKg,
        CapacityVolumeM3 = e.CapacityVolumeM3,
        IsRefrigerated = e.IsRefrigerated,
        MinSafeCelsius = e.MinSafeCelsius,
        MaxSafeCelsius = e.MaxSafeCelsius,
        DefaultDriverId = e.DefaultDriverId,
        HomeWarehouseId = e.HomeWarehouseId,
        TerritoryId = e.TerritoryId,
        CurrentOdometerKm = e.CurrentOdometerKm,
        FuelEfficiencyKmPerUnit = e.FuelEfficiencyKmPerUnit,
        IsOutOfService = e.IsOutOfService,
        OutOfServiceReason = e.OutOfServiceReason,
        NextServiceDueOn = e.NextServiceDueOn,
        NextServiceDueAtKm = e.NextServiceDueAtKm,
        IsActive = e.IsActive,
        Note = e.Note,
        ComplianceRecords = e.ComplianceRecords.Where(c => !c.IsSuperseded).Select(c => c.ToDto()).ToList(),
    };

    public static VehicleComplianceDto ToDto(this VehicleCompliance e) => new()
    {
        Id = e.Id,
        VehicleId = e.VehicleId,
        VehicleRegistration = e.Vehicle?.RegistrationNumber,
        Kind = e.Kind,
        DocumentNumber = e.DocumentNumber,
        Issuer = e.Issuer,
        IssuedOn = e.IssuedOn,
        ExpiresOn = e.ExpiresOn,
        Cost = e.Cost,
        FileUrl = e.FileUrl,
        IsSuperseded = e.IsSuperseded,
        Note = e.Note,
        DaysToExpiry = (int)(e.ExpiresOn.Date - DateTime.UtcNow.Date).TotalDays,
    };

    public static DriverDto ToDto(this Driver e) => new()
    {
        Id = e.Id,
        Code = e.Code,
        FullName = e.FullName,
        Phone = e.Phone,
        PhotoUrl = e.PhotoUrl,
        EmployeeId = e.EmployeeId,
        FieldRepId = e.FieldRepId,
        PartnerId = e.PartnerId,
        LicenceNumber = e.LicenceNumber,
        LicenceClass = e.LicenceClass,
        LicenceExpiresOn = e.LicenceExpiresOn,
        DefaultVehicleId = e.DefaultVehicleId,
        JoinedOn = e.JoinedOn,
        LeftOn = e.LeftOn,
        IsActive = e.IsActive,
        Note = e.Note,
        DaysToLicenceExpiry = e.LicenceExpiresOn is null
            ? null
            : (int)(e.LicenceExpiresOn.Value.Date - DateTime.UtcNow.Date).TotalDays,
    };

    public static TripDto ToDto(this DeliveryTrip e) => new()
    {
        Id = e.Id,
        TripNumber = e.TripNumber,
        TripDate = e.TripDate,
        Status = e.Status,
        VehicleId = e.VehicleId,
        VehicleRegistration = e.Vehicle?.RegistrationNumber,
        DriverId = e.DriverId,
        DriverName = e.Driver?.FullName,
        HelperName = e.HelperName,
        RouteId = e.RouteId,
        WarehouseId = e.WarehouseId,
        FieldRepId = e.FieldRepId,
        PlannedStartAt = e.PlannedStartAt,
        PlannedEndAt = e.PlannedEndAt,
        DepartedAt = e.DepartedAt,
        ReturnedAt = e.ReturnedAt,
        OdometerOutKm = e.OdometerOutKm,
        OdometerInKm = e.OdometerInKm,
        DistanceKm = e.DistanceKm,
        PlannedDistanceKm = e.PlannedDistanceKm,
        FuelIssued = e.FuelIssued,
        PlannedStops = e.PlannedStops,
        CompletedStops = e.CompletedStops,
        FailedStops = e.FailedStops,
        PlannedValue = e.PlannedValue,
        DeliveredValue = e.DeliveredValue,
        CollectedAmount = e.CollectedAmount,
        ReturnValue = e.ReturnValue,
        TotalExpense = e.TotalExpense,
        FillRatePercent = e.FillRatePercent,
        OnTimePercent = e.OnTimePercent,
        CostPerDrop = e.CompletedStops == 0 ? 0 : Math.Round(e.TotalExpense / e.CompletedStops, 2),
        CancelReason = e.CancelReason,
        Note = e.Note,
        Stops = e.Stops.OrderBy(s => s.StopSequence).Select(s => s.ToDto()).ToList(),
        Expenses = e.Expenses.Select(x => x.ToDto()).ToList(),
    };

    public static TripSummaryDto ToSummary(this DeliveryTrip e) => new()
    {
        Id = e.Id,
        TripNumber = e.TripNumber,
        TripDate = e.TripDate,
        Status = e.Status,
        VehicleRegistration = e.Vehicle?.RegistrationNumber,
        DriverName = e.Driver?.FullName,
        PlannedStops = e.PlannedStops,
        CompletedStops = e.CompletedStops,
        FailedStops = e.FailedStops,
        PlannedValue = e.PlannedValue,
        DeliveredValue = e.DeliveredValue,
        CollectedAmount = e.CollectedAmount,
        FillRatePercent = e.FillRatePercent,
        ProgressPercent = Percent(e.CompletedStops + e.FailedStops, e.PlannedStops),
    };

    public static TripStopDto ToDto(this TripStop e) => new()
    {
        Id = e.Id,
        StopSequence = e.StopSequence,
        Status = e.Status,
        OutletId = e.OutletId,
        OutletName = e.Outlet?.Name,
        PartnerId = e.PartnerId,
        OrderId = e.OrderId,
        DestinationName = e.DestinationName,
        AddressLine = e.AddressLine,
        Latitude = e.Latitude,
        Longitude = e.Longitude,
        PlannedArrivalAt = e.PlannedArrivalAt,
        ArrivedAt = e.ArrivedAt,
        DepartedAt = e.DepartedAt,
        ServiceMinutes = e.ServiceMinutes,
        PlannedValue = e.PlannedValue,
        DeliveredValue = e.DeliveredValue,
        CollectedAmount = e.CollectedAmount,
        ReturnValue = e.ReturnValue,
        FailureReasonCodeId = e.FailureReasonCodeId,
        FailureNote = e.FailureNote,
        RescheduledFor = e.RescheduledFor,
        AttemptNumber = e.AttemptNumber,
        ProofOfDeliveryId = e.ProofOfDeliveryId,
        Note = e.Note,
        IsLate = e.PlannedArrivalAt is not null && e.ArrivedAt is not null && e.ArrivedAt > e.PlannedArrivalAt,
    };

    public static TripExpenseDto ToDto(this TripExpense e) => new()
    {
        Id = e.Id,
        TripId = e.TripId,
        TripNumber = e.Trip?.TripNumber,
        Kind = e.Kind,
        Amount = e.Amount,
        CurrencyCode = e.CurrencyCode,
        IncurredAt = e.IncurredAt,
        Reference = e.Reference,
        ReceiptUrl = e.ReceiptUrl,
        Note = e.Note,
        IsApproved = e.IsApproved,
        ApprovedAt = e.ApprovedAt,
        RejectionReason = e.RejectionReason,
    };

    public static PodDto ToDto(this ProofOfDelivery e) => new()
    {
        Id = e.Id,
        PodNumber = e.PodNumber,
        TripId = e.TripId,
        TripStopId = e.TripStopId,
        OrderId = e.OrderId,
        OutletId = e.OutletId,
        PartnerId = e.PartnerId,
        VisitId = e.VisitId,
        DeliveredAt = e.DeliveredAt,
        ReceivedByName = e.ReceivedByName,
        ReceivedByPhone = e.ReceivedByPhone,
        SignatureImageUrl = e.SignatureImageUrl,
        PhotoUrl = e.PhotoUrl,
        Latitude = e.Latitude,
        Longitude = e.Longitude,
        GeoValidation = e.GeoValidation,
        OtpVerified = e.OtpVerified,
        DeliveredValue = e.DeliveredValue,
        ShortValue = e.ShortValue,
        DamagedValue = e.DamagedValue,
        RejectedValue = e.RejectedValue,
        CollectedAmount = e.CollectedAmount,
        CreditNoteId = e.CreditNoteId,
        IsClean = e.IsClean,
        IsExceptionResolved = e.IsExceptionResolved,
        ExceptionNote = e.ExceptionNote,
        ReceiptSentTo = e.ReceiptSentTo,
        Note = e.Note,
        Lines = e.Lines.Select(l => l.ToDto()).ToList(),
    };

    public static PodLineDto ToDto(this PodLine e) => new()
    {
        Id = e.Id,
        OrderLineId = e.OrderLineId,
        ItemId = e.ItemId,
        ItemName = e.ItemName,
        BatchId = e.BatchId,
        BatchNumber = e.BatchNumber,
        Uom = e.Uom,
        DespatchedQuantity = e.DespatchedQuantity,
        AcceptedQuantity = e.AcceptedQuantity,
        ShortQuantity = e.ShortQuantity,
        DamagedQuantity = e.DamagedQuantity,
        RejectedQuantity = e.RejectedQuantity,
        Outcome = e.Outcome,
        UnitPrice = e.UnitPrice,
        CreditValue = e.CreditValue,
        ReasonCodeId = e.ReasonCodeId,
        PhotoUrl = e.PhotoUrl,
        Note = e.Note,
    };

    // ── Returns ──────────────────────────────────────────────────────────────

    public static ReturnDto ToDto(this ReturnAuthorisation e) => new()
    {
        Id = e.Id,
        ReturnNumber = e.ReturnNumber,
        Kind = e.Kind,
        Status = e.Status,
        OutletId = e.OutletId,
        OutletName = e.Outlet?.Name,
        PartnerId = e.PartnerId,
        VisitId = e.VisitId,
        FieldRepId = e.FieldRepId,
        RouteId = e.RouteId,
        OriginalOrderId = e.OriginalOrderId,
        OriginalInvoiceId = e.OriginalInvoiceId,
        OriginalInvoiceNumber = e.OriginalInvoiceNumber,
        RequestedOn = e.RequestedOn,
        ValidUntil = e.ValidUntil,
        ReasonCodeId = e.ReasonCodeId,
        ReasonNote = e.ReasonNote,
        ValuationBasis = e.ValuationBasis,
        ValuationPercent = e.ValuationPercent,
        CurrencyCode = e.CurrencyCode,
        ClaimedValue = e.ClaimedValue,
        ApprovedValue = e.ApprovedValue,
        CreditedValue = e.CreditedValue,
        ApprovedAt = e.ApprovedAt,
        RejectionReason = e.RejectionReason,
        CollectionTripId = e.CollectionTripId,
        CollectionVanUnitId = e.CollectionVanUnitId,
        CollectedAt = e.CollectedAt,
        LinkedClaimId = e.LinkedClaimId,
        CreditNoteId = e.CreditNoteId,
        PhotoUrl = e.PhotoUrl,
        Note = e.Note,
        IsExpired = e.ValidUntil is not null && e.ValidUntil.Value.Date < DateTime.UtcNow.Date
                    && e.Status is Domain.Enums.ReturnStatus.Requested or Domain.Enums.ReturnStatus.Approved,
        Lines = e.Lines.OrderBy(l => l.DisplayOrder).Select(l => l.ToDto()).ToList(),
    };

    public static ReturnSummaryDto ToSummary(this ReturnAuthorisation e) => new()
    {
        Id = e.Id,
        ReturnNumber = e.ReturnNumber,
        Kind = e.Kind,
        Status = e.Status,
        RequestedOn = e.RequestedOn,
        OutletName = e.Outlet?.Name,
        ClaimedValue = e.ClaimedValue,
        ApprovedValue = e.ApprovedValue,
        CurrencyCode = e.CurrencyCode,
        LineCount = e.Lines.Count,
    };

    public static ReturnLineDto ToDto(this ReturnAuthorisationLine e) => new()
    {
        Id = e.Id,
        DisplayOrder = e.DisplayOrder,
        ItemId = e.ItemId,
        ItemName = e.ItemName,
        ItemCode = e.ItemCode,
        BatchId = e.BatchId,
        BatchNumber = e.BatchNumber,
        ExpiryDate = e.ExpiryDate,
        Uom = e.Uom,
        UomFactor = e.UomFactor,
        RequestedQuantity = e.RequestedQuantity,
        ApprovedQuantity = e.ApprovedQuantity,
        ReceivedQuantity = e.ReceivedQuantity,
        UnitPrice = e.UnitPrice,
        UnitCost = e.UnitCost,
        LineValue = e.LineValue,
        ReasonCodeId = e.ReasonCodeId,
        PhotoUrl = e.PhotoUrl,
        Note = e.Note,
    };

    public static ReturnReceiptDto ToDto(this ReturnReceipt e) => new()
    {
        Id = e.Id,
        ReceiptNumber = e.ReceiptNumber,
        ReturnId = e.ReturnId,
        ReturnNumber = e.Return?.ReturnNumber,
        WarehouseId = e.WarehouseId,
        VanUnitId = e.VanUnitId,
        TripId = e.TripId,
        ReceivedAt = e.ReceivedAt,
        InspectedAt = e.InspectedAt,
        TotalValue = e.TotalValue,
        RestockedValue = e.RestockedValue,
        ScrappedValue = e.ScrappedValue,
        DestructionCertificateNumber = e.DestructionCertificateNumber,
        DestructionCertificateUrl = e.DestructionCertificateUrl,
        DestroyedOn = e.DestroyedOn,
        Note = e.Note,
        Lines = e.Lines.Select(l => l.ToDto()).ToList(),
    };

    public static ReturnReceiptLineDto ToDto(this ReturnReceiptLine e) => new()
    {
        Id = e.Id,
        ReturnLineId = e.ReturnLineId,
        ItemId = e.ItemId,
        ItemName = e.ItemName,
        BatchId = e.BatchId,
        BatchNumber = e.BatchNumber,
        ExpiryDate = e.ExpiryDate,
        Uom = e.Uom,
        ExpectedQuantity = e.ExpectedQuantity,
        ReceivedQuantity = e.ReceivedQuantity,
        AcceptedQuantity = e.AcceptedQuantity,
        RejectedQuantity = e.RejectedQuantity,
        UnitPrice = e.UnitPrice,
        UnitCost = e.UnitCost,
        LineValue = e.LineValue,
        Disposition = e.Disposition,
        PutawayBinId = e.PutawayBinId,
        ReasonCodeId = e.ReasonCodeId,
        Note = e.Note,
    };

    // ── Secondary sales ──────────────────────────────────────────────────────

    public static SecondarySaleDto ToDto(this SecondarySale e) => new()
    {
        Id = e.Id,
        DocumentNumber = e.DocumentNumber,
        PartnerId = e.PartnerId,
        PartnerName = e.Partner?.Name,
        OutletId = e.OutletId,
        OutletName = e.Outlet?.Name,
        OutletNameRaw = e.OutletNameRaw,
        CaptureMode = e.CaptureMode,
        UploadBatchId = e.UploadBatchId,
        SourceOrderId = e.SourceOrderId,
        SaleDate = e.SaleDate,
        TerritoryId = e.TerritoryId,
        RouteId = e.RouteId,
        CurrencyCode = e.CurrencyCode,
        SubTotal = e.SubTotal,
        DiscountAmount = e.DiscountAmount,
        SchemeAmount = e.SchemeAmount,
        TaxAmount = e.TaxAmount,
        TotalAmount = e.TotalAmount,
        ReturnAmount = e.ReturnAmount,
        LineCount = e.LineCount,
        TotalQuantity = e.TotalQuantity,
        IsMapped = e.IsMapped,
        MappingNote = e.MappingNote,
        IsPosted = e.IsPosted,
        Lines = e.Lines.Select(l => l.ToDto()).ToList(),
    };

    public static SecondarySaleLineDto ToDto(this SecondarySaleLine e) => new()
    {
        Id = e.Id,
        ItemId = e.ItemId,
        ItemName = e.ItemName,
        ItemCodeRaw = e.ItemCodeRaw,
        BrandId = e.BrandId,
        BatchId = e.BatchId,
        BatchNumber = e.BatchNumber,
        Uom = e.Uom,
        UomFactor = e.UomFactor,
        Quantity = e.Quantity,
        BaseQuantity = e.BaseQuantity,
        FreeQuantity = e.FreeQuantity,
        UnitPrice = e.UnitPrice,
        DiscountAmount = e.DiscountAmount,
        SchemeAmount = e.SchemeAmount,
        TaxAmount = e.TaxAmount,
        LineTotal = e.LineTotal,
        IsMapped = e.IsMapped,
        MappingNote = e.MappingNote,
    };

    public static SecondaryUploadDto ToDto(this SecondaryUploadBatch e) => new()
    {
        Id = e.Id,
        BatchNumber = e.BatchNumber,
        PartnerId = e.PartnerId,
        PartnerName = e.Partner?.Name,
        PeriodStart = e.PeriodStart,
        PeriodEnd = e.PeriodEnd,
        SubmittedAt = e.SubmittedAt,
        DueOn = e.DueOn,
        LatenessDays = e.LatenessDays,
        Status = e.Status,
        FileName = e.FileName,
        FileUrl = e.FileUrl,
        MappingProfileId = e.MappingProfileId,
        TotalRows = e.TotalRows,
        MappedRows = e.MappedRows,
        UnmappedRows = e.UnmappedRows,
        RejectedRows = e.RejectedRows,
        TotalValue = e.TotalValue,
        MappedValue = e.MappedValue,
        MappingAccuracyPercent = e.MappingAccuracyPercent,
        PostedAt = e.PostedAt,
        RejectionReason = e.RejectionReason,
        ValidationSummary = e.ValidationSummary,
    };

    public static MappingProfileDto ToDto(this SecondaryMappingProfile e) => new()
    {
        Id = e.Id,
        Name = e.Name,
        PartnerId = e.PartnerId,
        PartnerName = e.Partner?.Name,
        FileFormat = e.FileFormat,
        OutletColumn = e.OutletColumn,
        ItemColumn = e.ItemColumn,
        QuantityColumn = e.QuantityColumn,
        ValueColumn = e.ValueColumn,
        DateColumn = e.DateColumn,
        UomColumn = e.UomColumn,
        BatchColumn = e.BatchColumn,
        InvoiceColumn = e.InvoiceColumn,
        DateFormat = e.DateFormat,
        HeaderRowIndex = e.HeaderRowIndex,
        IsActive = e.IsActive,
        LastUsedAt = e.LastUsedAt,
    };

    public static StockDeclarationDto ToDto(this DistributorStockDeclaration e) => new()
    {
        Id = e.Id,
        DeclarationNumber = e.DeclarationNumber,
        PartnerId = e.PartnerId,
        PartnerName = e.Partner?.Name,
        AsOfDate = e.AsOfDate,
        SubmittedAt = e.SubmittedAt,
        DueOn = e.DueOn,
        LatenessDays = e.LatenessDays,
        CurrencyCode = e.CurrencyCode,
        TotalValue = e.TotalValue,
        NearExpiryValue = e.NearExpiryValue,
        ExpiredValue = e.ExpiredValue,
        DamagedValue = e.DamagedValue,
        LineCount = e.LineCount,
        DaysOfCover = e.DaysOfCover,
        IsVerified = e.IsVerified,
        Note = e.Note,
        Lines = e.Lines.Select(l => l.ToDto()).ToList(),
    };

    public static StockDeclarationLineDto ToDto(this DistributorStockLine e) => new()
    {
        Id = e.Id,
        ItemId = e.ItemId,
        ItemName = e.ItemName,
        ItemCodeRaw = e.ItemCodeRaw,
        BrandId = e.BrandId,
        BatchId = e.BatchId,
        BatchNumber = e.BatchNumber,
        ExpiryDate = e.ExpiryDate,
        Uom = e.Uom,
        UomFactor = e.UomFactor,
        Quantity = e.Quantity,
        BaseQuantity = e.BaseQuantity,
        UnitValue = e.UnitValue,
        TotalValue = e.TotalValue,
        Age0To30 = e.Age0To30,
        Age31To60 = e.Age31To60,
        Age61To90 = e.Age61To90,
        Age90Plus = e.Age90Plus,
        NearExpiryQuantity = e.NearExpiryQuantity,
        ExpiredQuantity = e.ExpiredQuantity,
        DamagedQuantity = e.DamagedQuantity,
        DaysOfCover = e.DaysOfCover,
        IsMapped = e.IsMapped,
    };

    public static StockNormDto ToDto(this StockNorm e) => new()
    {
        Id = e.Id,
        PartnerId = e.PartnerId,
        PartnerName = e.Partner?.Name,
        ItemId = e.ItemId,
        ItemName = e.ItemName,
        Uom = e.Uom,
        TargetDaysOfCover = e.TargetDaysOfCover,
        MinQuantity = e.MinQuantity,
        MaxQuantity = e.MaxQuantity,
        ReorderQuantity = e.ReorderQuantity,
        EffectiveFrom = e.EffectiveFrom,
        EffectiveTo = e.EffectiveTo,
        CurrentQuantity = e.CurrentQuantity,
        CurrentDaysOfCover = e.CurrentDaysOfCover,
        IsUnderStocked = e.IsUnderStocked,
        IsOverStocked = e.IsOverStocked,
        EvaluatedAt = e.EvaluatedAt,
    };

    public static ReconciliationDto ToDto(this SellInSellOutReconciliation e) => new()
    {
        Id = e.Id,
        PartnerId = e.PartnerId,
        PartnerName = e.Partner?.Name,
        PeriodStart = e.PeriodStart,
        PeriodEnd = e.PeriodEnd,
        ItemId = e.ItemId,
        ItemName = e.ItemName,
        BrandId = e.BrandId,
        Uom = e.Uom,
        OpeningQuantity = e.OpeningQuantity,
        PrimaryQuantity = e.PrimaryQuantity,
        SecondaryQuantity = e.SecondaryQuantity,
        ReturnQuantity = e.ReturnQuantity,
        DeclaredClosingQuantity = e.DeclaredClosingQuantity,
        ComputedClosingQuantity = e.ComputedClosingQuantity,
        VarianceQuantity = e.VarianceQuantity,
        VariancePercent = e.VariancePercent,
        VarianceValue = e.VarianceValue,
        Outcome = e.Outcome,
        IsExplained = e.IsExplained,
        ReasonCodeId = e.ReasonCodeId,
        ExplanationNote = e.ExplanationNote,
        ComputedAt = e.ComputedAt,
    };

    // ── Performance & planning ───────────────────────────────────────────────

    public static TargetDto ToDto(this SalesTarget e) => new()
    {
        Id = e.Id,
        Name = e.Name,
        Metric = e.Metric,
        Period = e.Period,
        Scope = e.Scope,
        PeriodStart = e.PeriodStart,
        PeriodEnd = e.PeriodEnd,
        TerritoryId = e.TerritoryId,
        RouteId = e.RouteId,
        FieldRepId = e.FieldRepId,
        PartnerId = e.PartnerId,
        OutletId = e.OutletId,
        CurrencyCode = e.CurrencyCode,
        TargetValue = e.TargetValue,
        AchievedValue = e.AchievedValue,
        AchievementPercent = e.AchievementPercent,
        ProRataTarget = e.ProRataTarget,
        ProjectedValue = e.ProjectedValue,
        LastPeriodValue = e.LastPeriodValue,
        SamePeriodLastYearValue = e.SamePeriodLastYearValue,
        IsPublished = e.IsPublished,
        LastComputedAt = e.LastComputedAt,
        Note = e.Note,
        Lines = e.Lines.OrderBy(l => l.DisplayOrder).Select(l => l.ToDto()).ToList(),
        PaceStatus = e.ProRataTarget == 0
            ? "OnTrack"
            : e.AchievedValue >= e.ProRataTarget * 1.05m ? "Ahead"
            : e.AchievedValue < e.ProRataTarget * 0.95m ? "Behind" : "OnTrack",
    };

    public static TargetLineDto ToDto(this TargetLine e) => new()
    {
        Id = e.Id,
        ItemId = e.ItemId,
        ItemName = e.ItemName,
        BrandId = e.BrandId,
        CategoryId = e.CategoryId,
        WeekNumber = e.WeekNumber,
        PhaseStart = e.PhaseStart,
        PhaseEnd = e.PhaseEnd,
        Uom = e.Uom,
        TargetValue = e.TargetValue,
        AchievedValue = e.AchievedValue,
        AchievementPercent = e.AchievementPercent,
        DisplayOrder = e.DisplayOrder,
    };

    public static KpiDto ToDto(this KpiSnapshot e) => new()
    {
        SnapshotDate = e.SnapshotDate,
        Scope = e.Scope,
        FieldRepId = e.FieldRepId,
        RouteId = e.RouteId,
        TerritoryId = e.TerritoryId,
        PartnerId = e.PartnerId,
        PlannedCalls = e.PlannedCalls,
        ActualCalls = e.ActualCalls,
        ProductiveCalls = e.ProductiveCalls,
        UnplannedCalls = e.UnplannedCalls,
        MissedCalls = e.MissedCalls,
        CoveragePercent = e.CoveragePercent,
        StrikeRatePercent = e.StrikeRatePercent,
        LinesPerCall = e.LinesPerCall,
        AverageBillValue = e.AverageBillValue,
        DropSize = e.DropSize,
        BillCount = e.BillCount,
        NewOutletsAdded = e.NewOutletsAdded,
        ActiveOutlets = e.ActiveOutlets,
        TotalOutlets = e.TotalOutlets,
        MustSellCompliancePercent = e.MustSellCompliancePercent,
        RangeSellingPercent = e.RangeSellingPercent,
        TimeInMarketMinutes = e.TimeInMarketMinutes,
        AverageTimePerCallMinutes = e.AverageTimePerCallMinutes,
        FirstCallAt = e.FirstCallAt,
        LastCallAt = e.LastCallAt,
        DistanceCoveredKm = e.DistanceCoveredKm,
        CurrencyCode = e.CurrencyCode,
        SalesValue = e.SalesValue,
        CollectionValue = e.CollectionValue,
        ReturnValue = e.ReturnValue,
        OverdueAmount = e.OverdueAmount,
        CollectionEfficiencyPercent = e.CollectionEfficiencyPercent,
    };

    public static ReplenishmentSuggestionDto ToDto(this ReplenishmentSuggestion e) => new()
    {
        Id = e.Id,
        TargetKind = e.TargetKind,
        PartnerId = e.PartnerId,
        VanUnitId = e.VanUnitId,
        WarehouseId = e.WarehouseId,
        SourceWarehouseId = e.SourceWarehouseId,
        ItemId = e.ItemId,
        ItemName = e.ItemName,
        Uom = e.Uom,
        CurrentStock = e.CurrentStock,
        InTransitStock = e.InTransitStock,
        ReorderPoint = e.ReorderPoint,
        SafetyStock = e.SafetyStock,
        TargetStock = e.TargetStock,
        SuggestedQuantity = e.SuggestedQuantity,
        AverageDailyDemand = e.AverageDailyDemand,
        DaysOfCover = e.DaysOfCover,
        LeadTimeDays = e.LeadTimeDays,
        UrgencyScore = e.UrgencyScore,
        EstimatedValue = e.EstimatedValue,
        GeneratedAt = e.GeneratedAt,
        IsActioned = e.IsActioned,
        IsDismissed = e.IsDismissed,
        DismissReason = e.DismissReason,
    };

    public static ForecastDto ToDto(this DemandForecast e) => new()
    {
        Id = e.Id,
        Name = e.Name,
        Basis = e.Basis,
        PeriodStart = e.PeriodStart,
        PeriodEnd = e.PeriodEnd,
        WarehouseId = e.WarehouseId,
        PartnerId = e.PartnerId,
        TerritoryId = e.TerritoryId,
        HistoryMonths = e.HistoryMonths,
        SeasonalityFactor = e.SeasonalityFactor,
        TrendFactor = e.TrendFactor,
        TotalForecastQuantity = e.TotalForecastQuantity,
        TotalForecastValue = e.TotalForecastValue,
        TotalActualQuantity = e.TotalActualQuantity,
        AccuracyPercent = e.AccuracyPercent,
        IsApproved = e.IsApproved,
        GeneratedAt = e.GeneratedAt,
        Note = e.Note,
        Lines = e.Lines.Select(l => l.ToDto()).ToList(),
    };

    public static ForecastLineDto ToDto(this ForecastLine e) => new()
    {
        Id = e.Id,
        ItemId = e.ItemId,
        ItemName = e.ItemName,
        BrandId = e.BrandId,
        Uom = e.Uom,
        HistoricAverage = e.HistoricAverage,
        ComputedQuantity = e.ComputedQuantity,
        OverrideQuantity = e.OverrideQuantity,
        OverrideReason = e.OverrideReason,
        FinalQuantity = e.FinalQuantity,
        ForecastValue = e.ForecastValue,
        ActualQuantity = e.ActualQuantity,
        AccuracyPercent = e.AccuracyPercent,
        DemandStdDeviation = e.DemandStdDeviation,
    };

    public static TransferRequestDto ToDto(this StockTransferRequest e) => new()
    {
        Id = e.Id,
        TransferNumber = e.TransferNumber,
        SourceWarehouseId = e.SourceWarehouseId,
        DestinationWarehouseId = e.DestinationWarehouseId,
        DestinationPartnerId = e.DestinationPartnerId,
        DestinationVanUnitId = e.DestinationVanUnitId,
        Status = e.Status,
        RequestedOn = e.RequestedOn,
        RequiredBy = e.RequiredBy,
        DispatchedAt = e.DispatchedAt,
        ReceivedAt = e.ReceivedAt,
        TripId = e.TripId,
        DispatchId = e.DispatchId,
        TotalQuantity = e.TotalQuantity,
        TotalValue = e.TotalValue,
        LineCount = e.LineCount,
        RejectionReason = e.RejectionReason,
        Note = e.Note,
    };

    // ── Compliance ───────────────────────────────────────────────────────────

    public static ColdChainCheckpointDto ToDto(this ColdChainCheckpoint e) => new()
    {
        Id = e.Id,
        Code = e.Code,
        Name = e.Name,
        Kind = e.Kind,
        WarehouseId = e.WarehouseId,
        VehicleId = e.VehicleId,
        VanUnitId = e.VanUnitId,
        OutletId = e.OutletId,
        OutletAssetId = e.OutletAssetId,
        MinSafeCelsius = e.MinSafeCelsius,
        MaxSafeCelsius = e.MaxSafeCelsius,
        CheckIntervalHours = e.CheckIntervalHours,
        Location = e.Location,
        SensorIdentifier = e.SensorIdentifier,
        LastReadingAt = e.LastReadingAt,
        LastReadingCelsius = e.LastReadingCelsius,
        IsInBreach = e.IsInBreach,
        IsActive = e.IsActive,
        Note = e.Note,
        IsCheckOverdue = e.LastReadingAt is null
            || e.LastReadingAt.Value.AddHours(e.CheckIntervalHours) < DateTime.UtcNow,
    };

    public static ColdChainLogDto ToDto(this ColdChainLog e) => new()
    {
        Id = e.Id,
        CheckpointId = e.CheckpointId,
        CheckpointName = e.Checkpoint?.Name,
        RecordedAt = e.RecordedAt,
        ReadingCelsius = e.ReadingCelsius,
        IsOutOfRange = e.IsOutOfRange,
        ExcursionMinutes = e.ExcursionMinutes,
        RecordedByName = e.RecordedByName,
        IsAutomatic = e.IsAutomatic,
        CorrectiveAction = e.CorrectiveAction,
        IsResolved = e.IsResolved,
        ResolvedAt = e.ResolvedAt,
        AffectedStockValue = e.AffectedStockValue,
        PhotoUrl = e.PhotoUrl,
        Note = e.Note,
    };

    public static RecallDto ToDto(this ProductRecall e) => new()
    {
        Id = e.Id,
        RecallNumber = e.RecallNumber,
        Title = e.Title,
        Status = e.Status,
        Severity = e.Severity,
        ItemId = e.ItemId,
        ItemName = e.ItemName,
        BatchId = e.BatchId,
        BatchNumber = e.BatchNumber,
        ExpiryDate = e.ExpiryDate,
        SupplierId = e.SupplierId,
        InitiatedOn = e.InitiatedOn,
        AnnouncedAt = e.AnnouncedAt,
        CompletedAt = e.CompletedAt,
        TargetCompletionOn = e.TargetCompletionOn,
        Reason = e.Reason,
        RegulatoryReference = e.RegulatoryReference,
        PublicNotice = e.PublicNotice,
        DespatchedQuantity = e.DespatchedQuantity,
        RecoveredQuantity = e.RecoveredQuantity,
        DestroyedQuantity = e.DestroyedQuantity,
        RecoveryPercent = e.RecoveryPercent,
        EstimatedValue = e.EstimatedValue,
        RecoveredValue = e.RecoveredValue,
        AffectedOutletCount = e.AffectedOutletCount,
        NotifiedOutletCount = e.NotifiedOutletCount,
        RespondedOutletCount = e.RespondedOutletCount,
        ClosureReport = e.ClosureReport,
        Note = e.Note,
        Notices = e.Notices.Select(n => n.ToDto()).ToList(),
    };

    public static RecallNoticeDto ToDto(this RecallOutletNotice e) => new()
    {
        Id = e.Id,
        OutletId = e.OutletId,
        OutletName = e.Outlet?.Name,
        PartnerId = e.PartnerId,
        DestinationName = e.DestinationName,
        Phone = e.Outlet?.OwnerPhone,
        SuppliedQuantity = e.SuppliedQuantity,
        ReturnedQuantity = e.ReturnedQuantity,
        Value = e.Value,
        NotifiedAt = e.NotifiedAt,
        NotificationChannel = e.NotificationChannel,
        AcknowledgedAt = e.AcknowledgedAt,
        CollectedAt = e.CollectedAt,
        ReturnId = e.ReturnId,
        IsClosed = e.IsClosed,
        Note = e.Note,
    };

    public static ReasonCodeDto ToDto(this ReasonCode e) => new()
    {
        Id = e.Id,
        Code = e.Code,
        Name = e.Name,
        Surface = e.Surface,
        DisplayOrder = e.DisplayOrder,
        RequiresNote = e.RequiresNote,
        RequiresApproval = e.RequiresApproval,
        IsRecoverable = e.IsRecoverable,
        IsNegative = e.IsNegative,
        ColorHex = e.ColorHex,
        IconName = e.IconName,
        IsSystem = e.IsSystem,
        IsActive = e.IsActive,
        Description = e.Description,
    };

    public static NotificationDto ToDto(this DistributionNotification e) => new()
    {
        Id = e.Id,
        Kind = e.Kind,
        Severity = e.Severity,
        Title = e.Title,
        Body = e.Body,
        ReferenceId = e.ReferenceId,
        ReferenceType = e.ReferenceType,
        ActionRoute = e.ActionRoute,
        RaisedAt = e.RaisedAt,
        ReadAt = e.ReadAt,
        DismissedAt = e.DismissedAt,
        IsRead = e.ReadAt is not null,
    };

    // ── Helpers ──────────────────────────────────────────────────────────────

    /// <summary>Percentage of a denominator that may legitimately be zero.</summary>
    public static decimal Percent(decimal numerator, decimal denominator)
        => denominator == 0 ? 0 : Math.Round(numerator / denominator * 100, 2);

    private static bool IsOpen(Domain.Enums.ClaimStatus status) => status
        is Domain.Enums.ClaimStatus.Submitted
        or Domain.Enums.ClaimStatus.UnderReview
        or Domain.Enums.ClaimStatus.QueryRaised
        or Domain.Enums.ClaimStatus.Resubmitted
        or Domain.Enums.ClaimStatus.Approved
        or Domain.Enums.ClaimStatus.PartiallyApproved;
}
