<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>75eeb947-88ae-4bc9-a45e-bde30ec16582</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Modules\Crm\Crm.Api\Crm.Api.csproj" />
    <ProjectReference Include="..\Modules\Crm\Crm.Application\Crm.Application.csproj" />
    <ProjectReference Include="..\Modules\Crm\Crm.Domain\Crm.Domain.csproj" />
    <ProjectReference Include="..\Modules\Crm\Crm.Infrastructure\Crm.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Manufacturing\Manufacturing.Api\Manufacturing.Api.csproj" />
    <ProjectReference Include="..\Modules\Manufacturing\Manufacturing.Infrastructure\Manufacturing.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Auth\Auth.Api\Auth.Api.csproj" />
    <ProjectReference Include="..\Modules\Auth\Auth.Infrastructure\Auth.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Core\Core.Api\Core.Api.csproj" />
    <ProjectReference Include="..\Modules\Core\Core.Infrastructure\Core.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Core\Core.Application\Core.Application.csproj" />
    <ProjectReference Include="..\Modules\Core\Core.Domain\Core.Domain.csproj" />
    <ProjectReference Include="..\Modules\Accounting\Accounting.Api\Accounting.Api.csproj" />
    <ProjectReference Include="..\Modules\Accounting\Accounting.Infrastructure\Accounting.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Accounting\Accounting.Application\Accounting.Application.csproj" />
    <ProjectReference Include="..\Modules\Accounting\Accounting.Domain\Accounting.Domain.csproj" />
    <ProjectReference Include="..\Modules\Hr\Hr.Api\Hr.Api.csproj" />
    <ProjectReference Include="..\Modules\Hr\Hr.Infrastructure\Hr.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Hr\Hr.Application\Hr.Application.csproj" />
    <ProjectReference Include="..\..\Nexcore.SharedKernel\Nexcore.SharedKernel.csproj" />
    <ProjectReference Include="..\Modules\Inventory\Inventory.Api\Inventory.Api.csproj" />
    <ProjectReference Include="..\Modules\Inventory\Inventory.Infrastructure\Inventory.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Sales\Sales.Api\Sales.Api.csproj" />
    <ProjectReference Include="..\Modules\Sales\Sales.Infrastructure\Sales.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Restaurant\Restaurant.Api\Restaurant.Api.csproj" />
    <ProjectReference Include="..\Modules\Distribution\Distribution.Api\Distribution.Api.csproj" />
    <ProjectReference Include="..\Modules\Distribution\Distribution.Infrastructure\Distribution.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Restaurant\Restaurant.Infrastructure\Restaurant.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Procurement\Procurement.Api\Procurement.Api.csproj" />
    <ProjectReference Include="..\Modules\Procurement\Procurement.Infrastructure\Procurement.Infrastructure.csproj" />
  </ItemGroup>

</Project>
