namespace Hr.Application.DTOs;

public class OnboardingTaskDto
{
    public Guid Id { get; set; }
    public Guid CompanyId { get; set; }
    public string TaskCode { get; set; } = string.Empty;
    public Guid ApplicationId { get; set; }
    public Guid? EmployeeId { get; set; }
    public Guid? CandidateId { get; set; }
    public Guid? OnboardingTaskTemplateId { get; set; }
    public string TaskName { get; set; } = string.Empty;
    public string TaskCategory { get; set; } = string.Empty;
    public string? TaskDescription { get; set; }
    public Guid AssignedToEmployeeId { get; set; }
    public DateTime DueDate { get; set; }
    public DateTime? CompletionDate { get; set; }
    public Guid StatusLookupValueId { get; set; }
    public bool IsAutoGenerated { get; set; }
    public bool IsRequired { get; set; }
    public int SortOrder { get; set; }
    public Guid? DependsOnTaskId { get; set; }
    public bool RequiresDocumentUpload { get; set; }
    public bool RequiresManagerSignOff { get; set; }
    public bool EscalatedFlag { get; set; }
    public bool SLABreached { get; set; }
    public string? Notes { get; set; }
    public DateTime CreatedAt { get; set; }
    public DateTime? UpdatedAt { get; set; }
}

public class CreateOnboardingTaskDto
{
    public string TaskCode { get; set; } = string.Empty;
    public Guid ApplicationId { get; set; }
    public Guid? EmployeeId { get; set; }
    public Guid? CandidateId { get; set; }
    public Guid? OnboardingTaskTemplateId { get; set; }
    public string TaskName { get; set; } = string.Empty;
    public string TaskCategory { get; set; } = string.Empty;
    public string? TaskDescription { get; set; }
    public Guid AssignedToEmployeeId { get; set; }
    public DateTime DueDate { get; set; }
    public Guid StatusLookupValueId { get; set; }
    public bool IsRequired { get; set; } = true;
    public int SortOrder { get; set; }
    public Guid? DependsOnTaskId { get; set; }
    public bool RequiresDocumentUpload { get; set; }
    public bool RequiresManagerSignOff { get; set; }
    public string? Notes { get; set; }
}

public class UpdateOnboardingTaskDto
{
    public string? TaskName { get; set; }
    public string? TaskDescription { get; set; }
    public Guid? AssignedToEmployeeId { get; set; }
    public DateTime? DueDate { get; set; }
    public DateTime? CompletionDate { get; set; }
    public Guid? StatusLookupValueId { get; set; }
    public Guid? CompletedByEmployeeId { get; set; }
    public Guid? VerifiedByEmployeeId { get; set; }
    public DateTime? VerifiedAt { get; set; }
    public string? DocumentUrl { get; set; }
    public bool? EscalatedFlag { get; set; }
    public string? Notes { get; set; }
}
