using Sales.Application.DTOs;

namespace Sales.Application.Services.Interfaces;

/// <summary>
/// Central invoice + payment mechanism shared by every channel.
///
/// Whether an invoice is raised manually from the Sales module, created from a Sales Order,
/// or generated by a POS checkout, it flows through these same operations — so the resulting
/// <c>SalesInvoice</c> / <c>SalesPayment</c> records are identical and appear in the same lists.
/// </summary>
public interface ISalesInvoiceService
{
    /// <summary>Create a Draft invoice from explicit lines (manual invoicing).</summary>
    Task<SalesInvoiceDto> CreateAsync(CreateSalesInvoiceDto dto);

    /// <summary>
    /// Post (confirm) a Draft invoice → Issued. Sets the invoice date / payment reference and
    /// publishes the AR <c>SalesInvoicePostedEvent</c>.
    /// </summary>
    Task<SalesInvoiceDto> PostAsync(Guid invoiceId);

    /// <summary>
    /// Register a payment against a posted invoice. Creates the <c>SalesPayment</c> +
    /// <c>PaymentAllocation</c>, updates the invoice and order balances, and publishes the
    /// <c>SalesPaymentReceivedEvent</c>. Supports partial payments.
    /// </summary>
    Task<SalesInvoiceDto> RegisterPaymentAsync(Guid invoiceId, RegisterInvoicePaymentDto dto);
}
