<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <OutputType>Library</OutputType>
    <UserSecretsId>a20f6969-0019-406d-9b59-073fc496dea7</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Accounting.Application\Accounting.Application.csproj" />
    <ProjectReference Include="..\Accounting.Infrastructure\Accounting.Infrastructure.csproj" />
    <ProjectReference Include="..\Accounting.Contracts\Accounting.Contracts.csproj" />
    <ProjectReference Include="..\..\..\..\Nexcore.SharedKernel\Nexcore.SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Helpers\" />
  </ItemGroup>

</Project>
