
using Nexcore.SharedKernel;

namespace Hr.Domain.Entities;

public class OnboardingTask : BaseEntity
{
    public string TaskCode { get; set; } = string.Empty;
    public Guid ApplicationId { get; set; }
    public Guid? EmployeeId { get; set; }
    public Guid? CandidateId { get; set; }
    public Guid? OnboardingTaskTemplateId { get; set; }
    public string TaskName { get; set; } = string.Empty;
    public string TaskCategory { get; set; } = string.Empty;
    public string? TaskDescription { get; set; }
    public Guid AssignedToEmployeeId { get; set; }
    public DateTime DueDate { get; set; }
    public DateTime? CompletionDate { get; set; }
    public Guid StatusLookupValueId { get; set; }
    public bool IsAutoGenerated { get; set; }
    public string? Notes { get; set; }
    public bool IsRequired { get; set; }
    public int SortOrder { get; set; }
    public Guid? DependsOnTaskId { get; set; }
    public Guid? CompletedByEmployeeId { get; set; }
    public Guid? VerifiedByEmployeeId { get; set; }
    public DateTime? VerifiedAt { get; set; }
    public string? DocumentUrl { get; set; }
    public bool RequiresDocumentUpload { get; set; }
    public bool RequiresManagerSignOff { get; set; }
    public DateTime? ManagerSignOffDate { get; set; }
    public bool EscalatedFlag { get; set; }
    public DateTime? EscalatedAt { get; set; }
    public Guid? EscalatedToEmployeeId { get; set; }
    public int ReminderSentCount { get; set; }
    public DateTime? LastReminderSentAt { get; set; }
    public bool SLABreached { get; set; }
    public int? SLABreachHours { get; set; }
    public string? BlockedReason { get; set; }
    public Guid? CancelledByEmployeeId { get; set; }
    public DateTime? CancelledAt { get; set; }
    public string? CancelReason { get; set; }

    public Application? Application { get; set; }
    public Candidate? Candidate { get; set; }
    public Employee? Employee { get; set; }
    public Employee? AssignedToEmployee { get; set; }
    public Employee? CompletedByEmployee { get; set; }
    public Employee? VerifiedByEmployee { get; set; }
    public Employee? EscalatedToEmployee { get; set; }
    public Employee? CancelledByEmployee { get; set; }
    public OnboardingTaskTemplate? OnboardingTaskTemplate { get; set; }
    public OnboardingTask? DependsOnTask { get; set; }
    public LookupValue? StatusLookupValue { get; set; }
}
