<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <LangVersion>13.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
    <PackageReference Include="QuestPDF" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" />
    <PackageReference Include="ZXing.Net" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Sales.Tests.Integration" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Nexcore.SharedKernel\Nexcore.SharedKernel.csproj" />
    <ProjectReference Include="..\Sales.Domain\Sales.Domain.csproj" />
    <ProjectReference Include="..\Sales.Application\Sales.Application.csproj" />
  </ItemGroup>

</Project>
